### ISSUE TITLE
Compiling help: There is a bugs for me

### ISSUE THREAD

**Issue by realMohammadDev** [FNF-CNE-Devs/CodenameEngine#100]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)
![Screenshot_20230415_145226](https://user-images.githubusercontent.com/103966427/232224794-4f2073e9-90be-4a61-ac15-e1acca43b4e0.png)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ]Macos
[ ]Linux
##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by YoshiCrafter29** [comment]
Downgrade to 4.2.5. 4.3.0 have issues with macros & defines

**Comment by realMohammadDev** [comment]
> Downgrade to 4.2.5. 4.3.0 have issues with macros & defines

oh nothing, i mean the libvlc.xml doesn't since i still use a 4.2.5
