### ISSUE TITLE
Bug Report: [Hold note trails are off center from the note]

### ISSUE THREAD

**Issue by biomseed** [FNF-CNE-Devs/CodenameEngine#103]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x ] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
They are. To reproduce this, play a song with a down hold note.

**Comment by biomseed** [comment]
![image](https://user-images.githubusercontent.com/73907153/232237015-58168012-9704-4d31-89b6-1ed821fbfb0d.png)

**Comment by biomseed** [comment]
it's a tongue i can't unsee it

**Comment by biomseed** [comment]
the engine's gonna be out and this will probably still not be fixed

**Comment by FoxelTheFennic** [comment]
its being fixed 🥹

**Comment by NeeEoo** [comment]
This was fixed a while back,

![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/23155359/0b66e9e2-6a5c-4d28-9229-604c2ddf3b68)

**Comment by biomseed** [comment]
thank you
