### ISSUE TITLE
Compiling help: Expected Error...

### ISSUE THREAD

**Issue by AceThePan** [FNF-CNE-Devs/CodenameEngine#106]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[x] Mac

### Explain your issue
I'm getting this error all the time, I even tried to redownload the source code.
Heres the error: source/funkin/system/MusicBeatState.hx:114: characters 43-45 : Expected )

Can anybody help?

**Comment by biomseed** [comment]
Perhaps go to that line and look for a missing ")".

**Comment by AceThePan** [comment]
> Perhaps go to that line and look for a missing ")".
I don't think there is one missing

**Comment by SwickTheGreat** [comment]
update your haxe, it should fix the error

**Comment by AceThePan** [comment]
> update your haxe, it should fix the error

Thank you!
Sadly I get this error: source/funkin/utils/CoolUtil.hx:5: characters 8-29 : Type not found : flixel.sound.FlxSound
