### ISSUE TITLE
Compiling help: Type not found : flixel.sound.FlxSound

### ISSUE THREAD

**Issue by AceThePan** [FNF-CNE-Devs/CodenameEngine#108]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[x] Mac

### What happened?
I'm getting this error: source/funkin/utils/CoolUtil.hx:5: characters 8-29 : Type not found : flixel.sound.FlxSound

Can anybody help?

**Comment by NeeEoo** [comment]
Run update.sh

**Comment by Light0073** [comment]
haxelib remove flixel-addons
haxelib install flixel addons

**Comment by NeeEoo** [comment]
Running update.bat does the same, plus we use a custom version
