### ISSUE TITLE
Bug Report: bgFreaks switch back to their sprites for Senpai during the countdown on Roses

### ISSUE THREAD

**Issue by Pigswipe** [FNF-CNE-Devs/CodenameEngine#109]
### Which target are you using?
[X] Windows
[ ] Linux
[ ] Mac

### Explain your issue
The bgFreaks switch back to their sprites for Senpai during the countdown on Roses.
https://user-images.githubusercontent.com/50407359/232355459-ac3dc643-2ee5-47dd-8496-6376ef459c7c.mp4

**Comment by NeeEoo** [comment]
Fixed in e9c9c2b
