### ISSUE TITLE
Compiling help: libvlc.xml problem in my compile source?

### ISSUE THREAD

**Issue by realMohammadDev** [FNF-CNE-Devs/CodenameEngine#112]
WHY IS MY LIBVLC.XML DOESN'T WORKED TO COMPILE?
![Screenshot_20230418_160244](https://user-images.githubusercontent.com/103966427/232802094-6187167e-34e7-4d82-8e0d-035ceddfef62.png)
[ ] Windows

**Comment by NeeEoo** [comment]
Open cmd of desktop and type `haxelib set hxCodec 2.5.1`
