### ISSUE TITLE
Enhancement: Healthbar Colors

### ISSUE THREAD

**Issue by realMohammadDev** [FNF-CNE-Devs/CodenameEngine#113]
YoshMan, Why do you not making a options from healthbar colors and the old healthbars from green color?

**Comment by SwickTheGreat** [comment]
yoshi said that he would not like to add health bar colors a while back, you can implement them in your mod if you want them that badly.

**Comment by Foxplort** [comment]
There is an official mod for this on the official Discord server.

**Comment by YoshiCrafter29** [comment]
Won't be added in, but theres a script for it in the CNE Discord Server is you want to get it

**Comment by realMohammadDev** [comment]
> Won't be added in, but theres a script for it in the CNE Discord Server is you want to get it

but it wasted my space when i put all of these scripts

**Comment by realMohammadDev** [comment]
> Won't be added in, but theres a script for it in the CNE Discord Server is you want to get it

ok, but also, why you didn't updating this engine yet
