### ISSUE TITLE
Bug Report: May freeze if more than 2 splashes are used

### ISSUE THREAD

**Issue by soy-asterisk** [FNF-CNE-Devs/CodenameEngine#114]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)
Uses DeepL translation

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
1: Use a script like the following to change the splash in the middle of a song.
```haxe
function onPlayerHit(e) e.note.splash = (curBeat%2==0)?"secret":"default";
```
2: Freeze after displaying a certain number of splashes

**Comment by WizardMantis441** [comment]
fixed [here](https://github.com/FNF-CNE-Devs/CodenameEngine/commit/45fa33e2b65afffcb56e2c00ad76a989e23474df) by @NeeEoo
