### ISSUE TITLE
When updating the haxe it said this when i did lime test windows

### ISSUE THREAD

**Issue by JwallsRBLX** [FNF-CNE-Devs/CodenameEngine#115]
C:/Users/walls/Downloads/CodenameEngine-main/CodenameEngine-main/.haxelib/flxanimate/git/flxanimate/animate/FlxAnim.hx:29: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/walls/Downloads/CodenameEngine-main/CodenameEngine-main/.haxelib/flxanimate/git/flxanimate/FlxAnimate.hx:408: characters 97-105 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/funkin/backend/system/macros/ScriptsMacro.hx:31: characters 3-82 : Uncaught exception Invalid type definition
C:\HaxeToolkit\haxe\std/haxe/macro/Context.hx:674: characters 3-63 : Called from here
C:/Users/walls/Downloads/CodenameEngine-main/CodenameEngine-main/.haxelib/hscript-improved/git/hscript/UsingHandler.hx:98: characters 4-68 : Called from here
source/funkin/backend/system/macros/ScriptsMacro.hx:31: characters 3-82 : Called from here

**Comment by FoxelTheFennic** [comment]
are you on the latest haxe version and have you run update.bat?

**Comment by NeeEoo** [comment]
Codename doesnt support 4.3.0 and higher, yet. If you wanna compile codename, please downgrade to haxe 4.2.5
