### ISSUE TITLE
Compiling help: Can't find lib even though I already have it installed

### ISSUE THREAD

**Issue by Chidubemmo** [FNF-CNE-Devs/CodenameEngine#119]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x ] Windows
[ ] Linux
[ ] Mac

##### I can't build it because it says I don't have openfl installed even though I did? There isn't anything else to say to be hones
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by BushTrain460615** [comment]
try uninstalling then reinstalling it if that don't work idk

**Comment by NeeEoo** [comment]
Make sure you ran the `update.bat` file. If this doesn't work, feel free to send your error and reopen this issue.
