### ISSUE TITLE
How does image loading work in haxeflixel, more specifically this engine

### ISSUE THREAD

**Issue by rayanmargham** [FNF-CNE-Devs/CodenameEngine#120]
because the spritesheet images are 8k images how are they loaded without taking 200mb PER image?!??!?

**Comment by ACrazyTown** [comment]
I'm also interested in this, if its because of optimizations to the flixel fork CE uses the devs should definitely consider creating a PR to actual flixel

**Comment by NeeEoo** [comment]
This feature is called Gpu Textures, it basically offloads the texture to the gpu. The code in in [funkin/backend/system/OptimizedBitmapData.hx](https://github.com/FNF-CNE-Devs/CodenameEngine/blob/main/source/funkin/backend/system/OptimizedBitmapData.hx)
