### ISSUE TITLE
Bug Report: Engine crashing on startup

### ISSUE THREAD

**Issue by BernardoGP4504** [FNF-CNE-Devs/CodenameEngine#125]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
Whenever starting the newest codename engine build, the game crashes
![i did nothing wrong](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/101405920/602082c0-ac2e-4121-bd7e-2c73ef99791a)

[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by NeeEoo** [comment]
Please try and start the engine with this parameter `-nogpubitmap`

(Run in cmd `CodenameEngine.exe -nogpubitmap`)

**Comment by BernardoGP4504** [comment]
> Please try and start the engine with this parameter `-nogpubitmap`
> 
> (Run in cmd `CodenameEngine.exe -nogpubitmap`)

Thanks!
