### ISSUE TITLE
Bug Report: Game crashes when starting any song

### ISSUE THREAD

**Issue by BernardoGP4504** [FNF-CNE-Devs/CodenameEngine#126]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
Starting any song (even the base game ones) crashes the game.

You just have to start ANY song. No errors, direct crash

[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by NeeEoo** [comment]
Could you try compiling in debug, with the current information available, it isnt possible to replicate this bug

**Comment by BernardoGP4504** [comment]
> Could you try compiling in debug, with the current information available, it isnt possible to replicate this bug

But I'm not in a source code build and it takes forever to compile

**Comment by NeeEoo** [comment]
Okay just a quick test, but can you disable gpu textures in settings?

**Comment by BernardoGP4504** [comment]
> Okay just a quick test, but can you disable gpu textures in settings?

But there isn't a setting to do that and I'm already starting the engine using `-nogpubitmap`

**Comment by NeeEoo** [comment]
Please compile a debug build for us to see where its crashing, but kinda weird how its skipping the error handler. But still try and get a debug build

**Comment by NeeEoo** [comment]
Could you try and get the newest version and checking if it still happens, the crash log should appear now

**Comment by BernardoGP4504** [comment]
> Could you try and get the newest version and checking if it still happens, the crash log should appear now

I did and this appears now:
![whyyyy](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/101405920/d378e4ef-52da-49f3-9f86-b6bd7dda5d91)

the song I tried playing was the "Test" song

**Comment by BernardoGP4504** [comment]
> > > Could you try and get the newest version and checking if it still happens, the crash log should appear now
> > 
> > 
> > I did and this appears now: ![whyyyy](https://user-images.githubusercontent.com/101405920/253129932-d378e4ef-52da-49f3-9f86-b6bd7dda5d91.PNG)
> > the song I tried playing was the "Test" song
> 
> is the tankbg already in the folder or no

no, also is something weird about that FlxAnimateFrames trace? It appears in every song I tried

**Comment by NexIsDumb** [comment]
> > > > Could you try and get the newest version and checking if it still happens, the crash log should appear now
> 
> > > 
> 
> > > 
> 
> > > I did and this appears now: ![whyyyy](https://user-images.githubusercontent.com/101405920/253129932-d378e4ef-52da-49f3-9f86-b6bd7dda5d91.PNG)
> 
> > > the song I tried playing was the "Test" song
> 
> > 
> 
> > is the tankbg already in the folder or no
> 
> 
> 
> no, also is something weird about that FlxAnimateFrames trace? It appears in every song I tried

wait, so there are no folders with bgs stuff? plus dw that FlxAnimate trace is normal

**Comment by BernardoGP4504** [comment]
I even forgot about this
This issue was on a old laptop I had with 4GB ram 💀 

But now (since 2ish months) I have a new laptop that runs the engine flawless
So, we'll never know what the issue was originally, but thanks everyone here for the help
