### ISSUE TITLE
Enhancement: Update TODO.md

### ISSUE THREAD

**Issue by biomseed** [FNF-CNE-Devs/CodenameEngine#127]
## What is your suggestion, and why should it be implemented?
It will help keep track of the engine's progress

**Comment by SwickTheGreat** [comment]
the todo is updated, nothing on the todo has been changed so there are no updates yet.

**Comment by biomseed** [comment]
> the todo is updated, nothing on the todo has been changed so there are no updates yet.

![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/73907153/e8fc53fa-d963-4dda-a52c-e334f83513f4)
Are you sure about that?

**Comment by SwickTheGreat** [comment]
events are not finished yet and some don't work.
