### ISSUE TITLE
Question about mods

### ISSUE THREAD

**Issue by Bammmmmmmmmmmmm** [FNF-CNE-Devs/CodenameEngine#128]
So I wanna install mods but I can't find the folder

**Comment by WizardMantis441** [comment]
mods/your-mod/modstuffgoeshere

to open the available mods, press tab on the main menu

**Comment by WizardMantis441** [comment]
right here
![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/77557487/bff33b91-cf38-4659-bef3-47d40f401e85)
