### ISSUE TITLE
Bug Report: Ghost Tapping Crashes, Chart Zooming acts weirdly, Memory doesn't get cleared

### ISSUE THREAD

**Issue by ghost** [FNF-CNE-Devs/CodenameEngine#130]
### Bugs
-------------------------

- [x] Non Ghost Tapping Press Crashes
- [x] Chart Zooming is not capped
- [x] Chart Zooming behaves weirdly under too low/high zooms
- [x] Unused Cached Memory isn't cleared on state switch

### Explanation
-------------------------

* Disabling Ghost Tapping and pressing any key crashes (it's likely referencing a nulled note instead of passing a direction to the miss function but i don't know where codename stores input stuff to confirm this)

* Zooming in on the charter makes bitmaps flicker a LOT but doesn't really increase memory(?)
* Zooming out on the charter makes the memory increase (likely backdrops)

* Leaving a State doesn't clear unused cached memory for anything, MEANING THAT, you can stack the Chart Zoom-out memory leak until the game becomes unstable

-------------------------
### Proposal of fixes for this
* for the Non Ghost Tapping issue, instead of passing a note to the `noteMiss` function (if it is like that, that is), instead, simply pass a integer value representing a direction
* for the Chart Zooming issue, it should have been capped from the start, 0.5 minimum, 3 maximum
* for the State leaving issue, Just straight up adding a proper way of catching unused data from the cache and clearing it when leaving a state should be enough to address stackable memory leaks

### My Target platforms
Windows, Linux

--------------------
![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/93128334/8053e66c-1662-4c03-b554-4deb6684e5ee)
Ghost Tapping issue error report
--------------------
https://github.com/FNF-CNE-Devs/CodenameEngine/assets/93128334/839a07ba-e70d-4c29-92f5-0a38d240f308
## Zooming-in issue, EPILEPSY WARNING!!!
--------------------
can't really show the zooming out incident here since it crashes the recording software before I'm able to

**Comment by BeastlyGhost** [comment]
@NeeEoo close this i deleted that account LOL

**Comment by NeeEoo** [comment]
@BeastlyGhost no

**Comment by NeeEoo** [comment]
Idk how to close on mobile
