### ISSUE TITLE
Compiling help: [BRIEF DESCRIPTION / ERROR MESSAGE OUTPUT]

### ISSUE THREAD

**Issue by CJ77GT6R** [FNF-CNE-Devs/CodenameEngine#131]
[V ] Windows
[ ] Linux
[ ] Mac

**Comment by CJ77GT6R** [comment]
yes

**Comment by SwickTheGreat** [comment]
open the command prompt and run `haxelib list`, if you do not see `away3d` just run `haxelib install away3d`

**Comment by NeeEoo** [comment]
@CJ77GT6R any update on this?

**Comment by CJ77GT6R** [comment]
it worked
