### ISSUE TITLE
Bug Report: Game Crashes in the middle of charting

### ISSUE THREAD

**Issue by Mackery6969** [FNF-CNE-Devs/CodenameEngine#132]
### Which target are you using?
[x] Windows
[ ] Linux
[ ] Mac

### Explain your issue
I was in the middle of charting a song and the game crashed for no reason, and because there was no autosave it erased the entire chart.
##### Please check first if your issue hasn't already been reported yet.
How to reproduce
- idk it happens randomly in the chart editor.

**Comment by Mackery6969** [comment]
found out how to properly replicate it, shift click on a note.

**Comment by NeeEoo** [comment]
Fixed in 5f29c57
