### ISSUE TITLE
Bug Report: GF Notes bugged when as playerr

### ISSUE THREAD

**Issue by Bammmmmmmmmmmmm** [FNF-CNE-Devs/CodenameEngine#136]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[X ] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
Ok so, im doing a test port of a song, and i moved the notes from bfs side to gfs side (as seen in attached file), basically ingame the notes just wouldnt show, but you still had to play them

![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/82470343/e3db14e1-971c-47b9-b5c8-03ffc5eb5baa)

**Comment by NeeEoo** [comment]
This should be fixed now
