### ISSUE TITLE
Bug Report: Copying with nothing selected in chart editor crashes.

### ISSUE THREAD

**Issue by BCT2006** [FNF-CNE-Devs/CodenameEngine#139]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x ] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
Copying with nothing selected crashes the game

![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/51544115/66a3f68a-b8c6-4b3c-ba71-3c3a65c30dba)

https://github.com/FNF-CNE-Devs/CodenameEngine/assets/51544115/d96c5e98-4302-493d-8fa5-948b10fceced

[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by NeeEoo** [comment]
Fixed in 256c7ae
