### ISSUE TITLE
Opening older charts (Aprill 22 2023) on the newest version in the chart editor crashes the game

### ISSUE THREAD

**Issue by Mooshie318** [FNF-CNE-Devs/CodenameEngine#144]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

### Explain your issue
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
Like it says in the title, when I open any older chart from (April 22, 2023) in the chart editor on the newer versions, the game crashes.

### Bug tutorial:
- Download codename from April 22, 2023
- Download update from June 2023
- Open the chart editor onto any song
- Crash
<img width="642" alt="help help " src="https://github.com/FNF-CNE-Devs/CodenameEngine/assets/84255571/e9501db9-cf9c-46fd-86b0-d8f7388b7df8">

**Comment by NeeEoo** [comment]
Could you provide a chart?

**Comment by Mooshie318** [comment]
[here](https://www.mediafire.com/file/15299rv2nw6csao/hard.json/file) This is from Bopeebo

**Comment by Mooshie318** [comment]
nvm I figured it out, the version I was on was missing all the event-related images
