### ISSUE TITLE
Compiling help: problem with hxCodec

### ISSUE THREAD

**Issue by sonis32yt** [FNF-CNE-Devs/CodenameEngine#152]
![i nede le help](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/96783865/e9cf783a-d647-472b-857c-c072c793d85a)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

### Explain your issue
it always says "Error: Could not find haxelib "hxCodec", does it need to be installed?" whenever i do lime test windows even tho i do have hxCodec installed and updated, also yes i have done update.bat mutiple times and it still shows the error

**Comment by sonis32yt** [comment]
![i nede le help](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/96783865/99b1af98-785a-4d6e-8b46-4941804c1596)

**Comment by NeeEoo** [comment]
Can you try compiling after updating?

**Comment by NeeEoo** [comment]
Heck i meant restarting

**Comment by biomseed** [comment]
Install the git hxCodec instead of the haxelib version. should be easy.

**Comment by NeeEoo** [comment]
Actually we use a custom hxCodec repo

**Comment by biomseed** [comment]
Switch to that version, you must have switched to the haxelib version at one point

**Comment by NeeEoo** [comment]
This issue was made before we made the fork of hxcodec
