### ISSUE TITLE
Typo Report: [Typo In Chart Editor!]

### ISSUE THREAD

**Issue by KOREACHE** [FNF-CNE-Devs/CodenameEngine#158]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[Windows]: 

### Explain your issue
Save Meta Not Save Mata.
![Screenshot 2023-07-01 064011](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/130187021/c0a8a7d8-e85e-43f3-8f8b-33af3f141382)

**Comment by biomseed** [comment]
WE WIN

**Comment by KOREACHE** [comment]
> WE WIN

We Do!
