### ISSUE TITLE
Bug Report: Pressing R Key In Chart Editor Does This:

### ISSUE THREAD

**Issue by KOREACHE** [FNF-CNE-Devs/CodenameEngine#162]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[Windows]:

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

Pressing R Key ANYWHERE (Even When Trying To Use Events)  In Chart Editor Does This:
![Screenshot 2023-07-02 105330](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/130187021/06ddb2e1-89bd-40af-9b67-f22674465d69)

**Comment by WizardMantis441** [comment]
do you have any addons in your `addons` folder? iirc there's no code for even checking the R key.

**Comment by KOREACHE** [comment]
> do you have any addons in your `addons` folder? iirc there's no code for even checking the R key.

No, Its Just Base Code name With No Changes What-So-Ever.
![Screenshot 2023-07-06 114019](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/130187021/58f63722-a630-40ab-b22d-c16927eefc17)
