### ISSUE TITLE
Bug Report: Camera position in character editor doesnt work properly

### ISSUE THREAD

**Issue by PSYCHOVICH229** [FNF-CNE-Devs/CodenameEngine#167]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

### Explain your issue
So
![Снимок экрана 2023-07-03 165133](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/130473579/2e3c61ba-79c8-41b9-8839-6065f6aeb576)

![Снимок экрана 2023-07-03 165203](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/130473579/04088b11-b4d9-4114-9011-bd9bc968831e)

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by KOREACHE** [comment]
It's Flipped. Up Is Down, Down Is Up, Left is Right And Right Is Left
