### ISSUE TITLE
Compiling help: Couldn't find a included file hxCodec 2.6.1

### ISSUE THREAD

**Issue by APurples** [FNF-CNE-Devs/CodenameEngine#183]
### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

### Explain your issue
When I try to compile I always get an error message saying "Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/2,6,1/vlc/lib/LibVLCBuild.xml" I already installed hxCodec 2.6.1 but it didn't work. I even ran update.bat and installed everything on there. Any help please?
![ihatecompilingcodename](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/123270096/0f97b6cc-fe67-4d99-8cba-6c8da83e8f15)

**Comment by MemeHovy** [comment]
have you already run update.bat?

**Comment by APurples** [comment]
never mind i fixed it

**Comment by MemeHovy** [comment]
![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/124418090/15afa0f2-5461-4a21-bc50-d44f2833a11d)
