### ISSUE TITLE
Compiling help: [it is not detecting the default.json/[lime.utils.Preloader] There is no asset library with an ID of "default"]

### ISSUE THREAD

**Issue by SomeoneUnknownForReal** [FNF-CNE-Devs/CodenameEngine#219]
[lime.utils.Preloader] There is no asset library with an ID of "default"
I am using windows 11 64bits home insider preview 22h2.

### Which target are you using?
As I said, Windows 11.

[ x ] Windows
[ ] Linux
[ ] Mac

### Explain your issue
I was compiling codename. I only turned on the update.bat before compiling. I saw the message to downgrade haxe to 4.2.5 so I did it but I didn't remove the 4.3.1, it may be the issue.  Everything was right until it turned on (I used lime test windows). The error showed and I didn't know what to do because there weren't many websites with a solution, but if there was a one, it didn't work.

##### Please check first if your issue haven't already been reported yet, and make sure you ran the `update.bat` file before building.
It wasn't reported yet.

![obraz_2023-11-27_202848522](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/139068218/8b71d538-4925-4588-b737-5d30910feb6b)

**Comment by MemeHovy** [comment]
currently, it’s a issue with lime, not the engine

**Comment by SomeoneUnknownForReal** [comment]
oh

**Comment by SomeoneUnknownForReal** [comment]
Okay I found a version that will work: lime 8.0.2
