### ISSUE TITLE
Can any one Help

### ISSUE THREAD

**Issue by zeadd21g1233** [FNF-CNE-Devs/CodenameEngine#220]
[ ] Windows
[ ] Linux
[ ] Mac
[x] Html

does this engine support Html Compile ?
then i try to compile it its give me Error:

(unknown) : You cannot access the sys package while targeting js (for sys.db.Connection)

**Comment by DoingYourGirl5** [comment]
I think this error has to with something with the version of lime you're using if im wrong

**Comment by NexIsDumb** [comment]
nope currently html is bugged
