### ISSUE TITLE
Too many arguments

### ISSUE THREAD

**Issue by Suslagreally** [FNF-CNE-Devs/CodenameEngine#222]
[*] Windows
[ ] Linux
[ ] Mac

So, when I try to launch and compile the game 
![ye](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/153198257/f1e4dd19-1883-424c-986d-41c4af27912c)

this happens...
what do i do?

**Comment by MemeHovy** [comment]
did you run update.bat?

**Comment by Suslagreally** [comment]
> did you run update.bat?

yeah, i did. I could do it again tho

**Comment by Suslagreally** [comment]
> > did you run update.bat?
> 
> yeah, i did. I could do it again tho
Doesn't work

**Comment by liri1222335456** [comment]
haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc 0913b0d6c349157913d7cae7a1cba0ca108462af

**Comment by Suslagreally** [comment]
> haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc 0913b0d6c349157913d7cae7a1cba0ca108462af

Thanks, It solved one problem... but
![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/153198257/8c14ccf6-4378-44df-99de-95c025185c6d)
there is another one now

**Comment by Suslagreally** [comment]
> > haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc 0913b0d6c349157913d7cae7a1cba0ca108462af
> 
> Thanks, It solved one problem... but ![image](https://private-user-images.githubusercontent.com/153198257/289347124-8c14ccf6-4378-44df-99de-95c025185c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTgyMDUsIm5iZiI6MTcwMjIxNzkwNSwicGF0aCI6Ii8xNTMxOTgyNTcvMjg5MzQ3MTI0LThjMTRjY2Y2LTQzNzgtNDRkZi05OWRlLTk1YzAyNTE4NWM2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxNDE4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGI5Y2VlYzU4OGU2M2UxNWRiNTI4YmMzZmEyN2ZlMDE4OWIxMTI3YWQ0MGVhMTBmNGYwYzhmNzg5ZjE4MjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.046VVEtlGd4QG4hia8_6gP7asqQOrmpucvWoJTzz2HM) there is another one now

nvm I got It! Thanks for helping, guys!

**Comment by Suslagreally** [comment]
> > > haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc 0913b0d6c349157913d7cae7a1cba0ca108462af
> > 
> > 
> > Thanks, It solved one problem... but ![image](https://private-user-images.githubusercontent.com/153198257/289347124-8c14ccf6-4378-44df-99de-95c025185c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTgyMDUsIm5iZiI6MTcwMjIxNzkwNSwicGF0aCI6Ii8xNTMxOTgyNTcvMjg5MzQ3MTI0LThjMTRjY2Y2LTQzNzgtNDRkZi05OWRlLTk1YzAyNTE4NWM2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxNDE4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGI5Y2VlYzU4OGU2M2UxNWRiNTI4YmMzZmEyN2ZlMDE4OWIxMTI3YWQ0MGVhMTBmNGYwYzhmNzg5ZjE4MjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.046VVEtlGd4QG4hia8_6gP7asqQOrmpucvWoJTzz2HM) there is another one now
> 
> nvm I got It! Thanks for helping, guys!

yeah, issue is closed
