### ISSUE TITLE
Compiling help: "Too Many Arguments" Error

### ISSUE THREAD

**Issue by fffdsfdsfds** [FNF-CNE-Devs/CodenameEngine#225]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet, and make sure you ran the `update.bat` file before building.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
tryin to compile but i get these 2 errors everytime at the end: 
source/funkin/game/cutscenes/VideoCutscene.hx:163: characters 15-24 : Too many arguments
and
source/funkin/game/cutscenes/VideoCutscene.hx:88: characters 15-24 : Too many arguments

**Comment by liri1222335456** [comment]
haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc 0913b0d6c349157913d7cae7a1cba0ca108462af
