### ISSUE TITLE
VideoCutscence Compiling Issue

### ISSUE THREAD

**Issue by Cfgaming309** [FNF-CNE-Devs/CodenameEngine#230]
[x] Windows
[ ] Linux
[ ] Mac

i follow the steps but this showed up

source/funkin/game/cutscenes/VideoCutscene.hx:88: characters 15-24 : Too many arguments
source/funkin/game/cutscenes/VideoCutscene.hx:163: characters 15-24 : Too many arguments
source/funkin/game/cutscenes/VideoCutscene.hx:169: characters 34-58 : Cannot compare Float and haxe.Int64

you guys have this same issue??

**Comment by moxie-coder** [comment]
`haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc 0913b0d6c349157913d7cae7a1cba0ca108462af`
