### ISSUE TITLE
Bug Report: Senpai Pause Exit Bug

### ISSUE THREAD

**Issue by 2Schoolhouse** [FNF-CNE-Devs/CodenameEngine#237]
### Which target are you using?

[x ] Windows
[ ] Linux
[ ] Mac

### Explain your issue
For some reason, whenever I try to exit out of Senpai using the pause menu, the menu just... stays there. I'm not sure why it happens, but it does and I'm pretty sure that's not intentional. I haven't checked this with the other Week 6 songs yet. Luckily, it's possible to restart through F5, but other than that the only way I know how to overcome this is by quitting the game.

https://github.com/FNF-CNE-Devs/CodenameEngine/assets/111615291/4066926c-ab53-46be-9545-f87746dfe3b3

**Comment by NexIsDumb** [comment]
oh?
thanks i'll check in a few hours

**Comment by NexIsDumb** [comment]
okay I SWEAR ive checked everywhere but I cannot find this bug, are you sure you havent modify the script? Cause also I can't help but notice that the arrows tails you have are bugged too, instead of the current version:

![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/87421482/a4c5ce6b-87a1-4f12-a9b1-1344dbd3ab10)

**Comment by 2Schoolhouse** [comment]
I didn't add, change or remove any modifications to the source code or pause menu. As far as I'm aware I also used the "unsaved playtesting" Windows build to find this, so it might just be a bug in that version of Codename.
![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/111615291/c049c279-655a-4633-996e-a4a19b55c48d)

**Comment by NexIsDumb** [comment]
yeah use the latest version and tell me

**Comment by 2Schoolhouse** [comment]
Ah, looks like it closes to the freeplay menu as expected in the Cleanup action build. Thanks at least.
