### ISSUE TITLE
Bug Report: Character animation null object reference

### ISSUE THREAD

**Issue by mateus683** [FNF-CNE-Devs/CodenameEngine#254]
![Captura de tela 2024-03-11 190732](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/74618609/7ccded7d-a807-4737-8270-e4b4674cf1b3)

### Which target are you using?

[x ] Windows
[ ] Linux
[ ] Mac

### Explain your issue
I was trying out the character editor and i got the example on the wiki for the xml, i added whitty sprites and when i tried adding the idle the game simply crashed.
##### Please check first if your issue haven't already been reported yet.
i explored some parts and nothing

**Comment by 2Schoolhouse** [comment]
Are you sure that there could be some sort of error within the sprite XML file itself? Since the Whitty sprites themself are really old now, I figured I'd ask this first.

**Comment by mateus683** [comment]
> Are you sure that there could be some sort of error within the sprite XML file itself? Since the Whitty sprites themself are really old now, I figured I'd ask this first.

I can't actually try that out, I tried on XML and Sprite sheet generator and PE, they both worked fine. But I'm not sure if it's a different compatibility on CNE.

**Comment by 2Schoolhouse** [comment]
Have you tried perhaps checking if there are any errors inside of the character XML itself, then? For example, some incorrect syntax with an animation, knowing how you mention that it's related to animation.

**Comment by mateus683** [comment]
> Have you tried perhaps checking if there are any errors inside of the character XML itself, then? For example, some incorrect syntax with an animation, knowing how you mention that it's related to animation.

i didn't see that, but i got a recent mod character and it did the same thing (mod: 17menes and character files: bosta)

**Comment by 2Schoolhouse** [comment]
> i didn't see that, but i got a recent mod character and it did the same thing (mod: 17menes and character files: bosta)

Well then, if both the character files are json files, then it's best to replace them with actual character XML files. Codename does not support json files for its characters.

**Comment by CharlesCatYT** [comment]
> > Have you tried perhaps checking if there are any errors inside of the character XML itself, then? For example, some incorrect syntax with an animation, knowing how you mention that it's related to animation.
> 
> i didn't see that, but i got a recent mod character and it did the same thing (mod: 17menes and character files: bosta)

if youre using the characters' original psych json files, well... just use a psych json to codename xml converter as, like 2Schoolhouse said, codename does not support psych character files.

**Comment by mateus683** [comment]
> > > Have you tried perhaps checking if there are any errors inside of the character XML itself, then? For example, some incorrect syntax with an animation, knowing how you mention that it's related to animation.
> > 
> > 
> > i didn't see that, but i got a recent mod character and it did the same thing (mod: 17menes and character files: bosta)
> 
> if youre using the characters' original psych json files, well... just use a psych json to codename xml converter as, like 2Schoolhouse said, codename does not support psych character files.

I'm not using any json, I'm converting them into XML, like remaking the character with codename XML

**Comment by 2Schoolhouse** [comment]
> I'm not using any json, I'm converting them into XML, like remaking the character with codename XML

Then in that case it's likely an issue with the character XML itself. I'd recommend copying and pasting into the mod's characters folder one of the XMLs that are used by the base game, since vanilla FNF in the engine actually works as a mod of sorts, and then continue off from there in the Character Editor. Last I checked, sometimes the engine can be very picky with some things in terms of characters, though, so it might be best to also name your character's spritesheet the exact same name as the XML.

**Comment by mateus683** [comment]
i found out that i just got to rename everything from the character the same thing.
