### ISSUE TITLE
Need help Compiling 

### ISSUE THREAD

**Issue by thegamenig** [FNF-CNE-Devs/CodenameEngine#255]
C:/Users/users/Downloads/CodenameEngine-main/CodenameEngine-main/.haxelib/hscript-improved/git/hscript/macros/Utils.hx:195: characters 9-12 : Identifier 'EIs' is not part of haxe.macro.ExprDef (Suggestion: EIf)
C:/Users/users/Downloads/CodenameEngine-main/CodenameEngine-main/.haxelib/hscript-improved/git/hscript/macros/Utils.hx:195: characters 9-18 : Unrecognized pattern: EIs(e, t)
C:/Users/users/Downloads/CodenameEngine-main/CodenameEngine-main/.haxelib/hscript-improved/git/hscript/macros/ClassExtendMacro.hx:41: characters 10-20 : haxe.macro.ClassType has no field isAbstract
C:/Users/users/Downloads/CodenameEngine-main/CodenameEngine-main/.haxelib/hscript-improved/git/hscript/macros/ClassExtendMacro.hx:260: characters 20-25 : Too many arguments
source/funkin/backend/system/macros/HashLinkFixer.hx:44: characters 10-20 : haxe.macro.ClassType has no field isAbstract
source/funkin/backend/MusicBeatState.hx:124: characters 17-19 : Expected )

[x] Windows
[ ] Linux
[ ] Mac

**Comment by CharlesCatYT** [comment]
uhhhhhhhhhhhhhh
just use the action builds for now idk

**Comment by NeeEoo** [comment]
Use haxe 4.2.5 or 4.3.4

**Comment by thegamenig** [comment]
but now i got this error
C:\Users\Users\Downloads\CodenameEngine-main\CodenameEngine-main\export\release\windows\obj>setlocal 

enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by NexIsDumb** [comment]
> but now i got this error C:\Users\Users\Downloads\CodenameEngine-main\CodenameEngine-main\export\release\windows\obj>setlocal
> 
> enabledelayedexpansion Warning: Could not find Visual Studio VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC

did you install the visual studio code component as said in the installation guide?

**Comment by thegamenig** [comment]
yes

**Comment by thegamenig** [comment]
> yes but it not working

**Comment by thegamenig** [comment]
it not working

**Comment by NexIsDumb** [comment]
> it not working

so you didn't finish downloading the tool?

**Comment by thegamenig** [comment]
so how can i do that?

**Comment by NexIsDumb** [comment]
> so how can i do that?

literally by following the guide in the readme, under "how to build" if it wasn't oblv

**Comment by thegamenig** [comment]
ok i going to do that quick

**Comment by thegamenig** [comment]
i going to do that real quick

**Comment by NexIsDumb** [comment]
alr

**Comment by thegamenig** [comment]
C:\Users\Users\OneDrive\Desktop\CodenameEngine-main\CodenameEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion

Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by thegamenig** [comment]
"I don't know what to do

**Comment by thegamenig** [comment]
> "I don't know what to do
now

**Comment by thegamenig** [comment]
"I don't know what to do now

**Comment by NexIsDumb** [comment]
> "I don't know what to do now

huh are you sure it actually downloaded

**Comment by thegamenig** [comment]
yes i downloaded the CodenameEngine-main

**Comment by NexIsDumb** [comment]
> yes i downloaded the CodenameEngine-main

what, no i dont mean that
you gotta download the visual studio tool as said in the readme of this engine, did you even read the instructions??

**Comment by thegamenig** [comment]
yes i did

**Comment by NexIsDumb** [comment]
> yes i did

then you should also know that from the instruction i meant downloading the visual studio build

**Comment by thegamenig** [comment]
okay i'll be right back

**Comment by NexIsDumb** [comment]
alr

**Comment by thegamenig** [comment]
i give up...

**Comment by NexIsDumb** [comment]
> i give up...

did you follow the instructions of the readme??

**Comment by thegamenig** [comment]
yes i did

**Comment by thegamenig** [comment]
yes i did

**Comment by NexIsDumb** [comment]
> yes i did
> 

if you did, then tell me exactly what did you download

**Comment by thegamenig** [comment]
the Source Code/CodenameEngine-main

**Comment by NexIsDumb** [comment]
> the Source Code/CodenameEngine-main

again, for the like 3rd time, you ALSO gotta download the visual studio tool and the instructions are in the README

**Comment by moxie-coder** [comment]
> the Source Code/CodenameEngine-main

dude for the love of god, can you stop being so retarded and actually download visual studio for ffs, stop wasting everyone’s time and actually follow instructions in the damn readme

**Comment by NexIsDumb** [comment]
bro😭

**Comment by NexIsDumb** [comment]
> > the Source Code/CodenameEngine-main
> 
> dude for the love of god, can you stop being so retarded and actually download visual studio for ffs, stop wasting everyone’s time and actually follow instructions in the damn readme

no okay I think it's time for me to make a .bat or smth like in psych that downloads the tool
smth that tbh i would have never even thought of as I didn't think people could reach even this level

**Comment by moxie-coder** [comment]
> > > the Source Code/CodenameEngine-main
> > 
> > 
> > dude for the love of god, can you stop being so retarded and actually download visual studio for ffs, stop wasting everyone’s time and actually follow instructions in the damn readme
> 
> no okay I think it's time for me to make a .bat or smth like in psych that downloads the tool smth that tbh i would have never even thought of as I didn't think people could reach even this level

I didn't think so either, especially to a point where someone has never heard of botplay ever, even after using psych for so long they never heard of it

**Comment by moxie-coder** [comment]
I think this just captures how doomed we are as a species if people can reach this level of stupidity

**Comment by NexIsDumb** [comment]
lmfao

**Comment by usb-port-2** [comment]
Guys what's visual studio cod e..

**Comment by NexIsDumb** [comment]
> Guys what's visual studio cod e..

black magic directly from 1200

**Comment by NexIsDumb** [comment]
wtf😭

**Comment by CaptainDumb** [comment]
why the fuck is this shit still open

**Comment by NexIsDumb** [comment]
no idea tbh

**Comment by usb-port-2** [comment]
:3

**Comment by thegamenig** [comment]
Compiling Work!!

**Comment by PetscopF** [comment]
This whole conversation reads like one in an obscure history book to me, and I have no idea why.
