### ISSUE TITLE
I can't compile because lime issues please help

### ISSUE THREAD

**Issue by FacunMax** [FNF-CNE-Devs/CodenameEngine#260]
[X ] Windows
[ ] Linux
[ ] Mac

Well, I ran the update.bat and downloaded all the libraries except lime. here the error: "Error: [file_contents,C:\Users\Usuario\Downloads\save source\CodenameEngine-main\.haxelib\lime/.current]" I don't know why this happens. I have the folder and the rar of the lime but well I don't know how to solve this. (and no, removing and installing lime again doesn't work)
![Captura de pantalla (668)](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/148605202/e0a8a298-eab6-4959-bafd-9a01dd21c088)
![Captura de pantalla (667)](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/148605202/d462bd83-3c06-42f5-b33e-b9665d8353fa)

**Comment by NexIsDumb** [comment]
could you try to see what happens if you delete both lime folder and zip and then reinstall?
cuz it cannot find the .current file inside lime apparently

**Comment by FacunMax** [comment]
> could you try to see what happens if you delete both lime folder and zip and then reinstall? instead of just uninstalling cuz it cannot find the .current file inside the lime folder apparently

now it say "Error: [file_open,C:\Users\Usuario\Downloads\save source\CodenameEngine-main\.haxelib\lime/8,0,2/dependencies/angle/d3dcompiler_47.dll]"

**Comment by NexIsDumb** [comment]
> > could you try to see what happens if you delete both lime folder and zip and then reinstall? instead of just uninstalling cuz it cannot find the .current file inside the lime folder apparently
> 
> now it say "Error: [file_open,C:\Users\Usuario\Downloads\save source\CodenameEngine-main\.haxelib\lime/8,0,2/dependencies/angle/d3dcompiler_47.dll]"

okay thats odd
try at this point to delete the entire .haxelib folder and rerun the bat
also check if the antivirus is deleting anything

**Comment by FacunMax** [comment]
> > > could you try to see what happens if you delete both lime folder and zip and then reinstall? instead of just uninstalling cuz it cannot find the .current file inside the lime folder apparently
> > 
> > 
> > now it say "Error: [file_open,C:\Users\Usuario\Downloads\save source\CodenameEngine-main.haxelib\lime/8,0,2/dependencies/angle/d3dcompiler_47.dll]"
> 
> okay thats odd try at this point to delete the entire .haxelib folder and rerun the bat also check if the antivirus is deleting anything

well uhh....
![Captura de pantalla (670)](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/148605202/ca146174-f040-431e-9524-7f9b28701593)
![Captura de pantalla (671)](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/148605202/13d6f90a-7e0c-445f-a971-bb961372d714)
![Captura de pantalla (672)](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/148605202/48f4b755-3826-45e4-9f59-15fe876b5831)
![jo32MjlR_400x400](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/148605202/65e39b08-aebc-4740-b033-8b0f06f073da)

**Comment by FacunMax** [comment]
also i have the antivirus turned off

**Comment by 2Schoolhouse** [comment]
> ![Captura de pantalla (670)](https://private-user-images.githubusercontent.com/148605202/315842629-ca146174-f040-431e-9524-7f9b28701593.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzE5MzgsIm5iZiI6MTcxMTA3MTYzOCwicGF0aCI6Ii8xNDg2MDUyMDIvMzE1ODQyNjI5LWNhMTQ2MTc0LWYwNDAtNDMxZS05NTI0LTdmOWIyODcwMTU5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwMTQwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzI3OWRkOTkwYTg1YjhhOWJkY2ZhMmI4Y2ViYTQ0Njk1NzZlNzNlNDY2ZjVhYWIyNjgzZGNhMzM0ZTNkZDk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YfPdZur6z1thi131Q69jEcFU9usns6AWRP6P-6GH1uE)

From the looks of it, you don't have lime installed. As far as I'm aware, lime is required for the game to function in the first place, so I'd suggest running what the error tells you first BEFORE running the `lime test windows` command.

**Comment by FacunMax** [comment]
> > ![Captura de pantalla (670)](https://private-user-images.githubusercontent.com/148605202/315842629-ca146174-f040-431e-9524-7f9b28701593.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzE5MzgsIm5iZiI6MTcxMTA3MTYzOCwicGF0aCI6Ii8xNDg2MDUyMDIvMzE1ODQyNjI5LWNhMTQ2MTc0LWYwNDAtNDMxZS05NTI0LTdmOWIyODcwMTU5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwMTQwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzI3OWRkOTkwYTg1YjhhOWJkY2ZhMmI4Y2ViYTQ0Njk1NzZlNzNlNDY2ZjVhYWIyNjgzZGNhMzM0ZTNkZDk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YfPdZur6z1thi131Q69jEcFU9usns6AWRP6P-6GH1uE)
> 
> From the looks of it, you don't have lime installed. As far as I'm aware, lime is required for the game to function in the first place, so I'd suggest running what the error tells you first BEFORE running the `lime test windows` command.

look at the next screenshots

**Comment by FacunMax** [comment]
i have installed but it takes like is not

**Comment by 2Schoolhouse** [comment]
> look at the next screenshots

Well then, have you at least tried to first uninstall it (for example through command prompt) and then reinstall it through command prompt back?

**Comment by FacunMax** [comment]
> > look at the next screenshots
> 
> Well then, have you at least tried to first uninstall it (for example through command prompt) and then reinstall it through command prompt back?

yes and it got the same error

**Comment by 2Schoolhouse** [comment]
> yes and it got the same error

Was it the same error with lime not being installed, or one of the previous errors?

**Comment by FacunMax** [comment]
> > yes and it got the same error
> 
> Was it the same error with lime not being installed, or one of the previous errors?

sorry for late and both

**Comment by 2Schoolhouse** [comment]
> sorry for late and both

Then I guess maybe remove the `.haxelib` folder from your source code folder? I have never really experienced this kind of issue before.

**Comment by Robert124l** [comment]
> > sorry for late and both
> 
> Then I guess maybe remove the `.haxelib` folder from your source code folder? I have never really experienced this kind of issue before.

(secondary account) bro i will delete the entire library if i do that

**Comment by moxie-coder** [comment]
> > > sorry for late and both
> > 
> > 
> > Then I guess maybe remove the `.haxelib` folder from your source code folder? I have never really experienced this kind of issue before.
> 
> (secondary account) bro i will delete the entire library if i do that

just run the update.bat again after deleting it, it won’t delete your global haxelibs, it’ll only delete the local ones you stupid bastard

**Comment by Robert124l** [comment]
> > > > sorry for late and both
> > > 
> > > 
> > > Then I guess maybe remove the `.haxelib` folder from your source code folder? I have never really experienced this kind of issue before.
> > 
> > 
> > (secondary account) bro i will delete the entire library if i do that
> 
> just run the update.bat again after deleting it, it won’t delete your global haxelibs, it’ll only delete the local ones you stupid bastard

i knooow, I was talking about the engine library

**Comment by moxie-coder** [comment]
> > > > > sorry for late and both
> > > > 
> > > > 
> > > > Then I guess maybe remove the `.haxelib` folder from your source code folder? I have never really experienced this kind of issue before.
> > > 
> > > 
> > > (secondary account) bro i will delete the entire library if i do that
> > 
> > 
> > just run the update.bat again after deleting it, it won’t delete your global haxelibs, it’ll only delete the local ones you stupid bastard
> 
> i knooow, I was talking about the engine library

it’ll just make a new one when you run update.bat, it’s not even hard to make you just run haxelib newrepo

**Comment by FacunMax** [comment]
> > > > > > sorry for late and both
> > > > > 
> > > > > 
> > > > > Then I guess maybe remove the `.haxelib` folder from your source code folder? I have never really experienced this kind of issue before.
> > > > 
> > > > 
> > > > (secondary account) bro i will delete the entire library if i do that
> > > 
> > > 
> > > just run the update.bat again after deleting it, it won’t delete your global haxelibs, it’ll only delete the local ones you stupid bastard
> > 
> > 
> > i knooow, I was talking about the engine library
> 
> it’ll just make a new one when you run update.bat, it’s not even hard to make you just run haxelib newrepo, the engine library isn’t even a thing wtf do you mean? like just delete the .haxelib folder and run the update.bat again

im back, i ALREADY do that one million times, even i said it here before

**Comment by FacunMax** [comment]
> > > > > > sorry for late and both
> > > > > 
> > > > > 
> > > > > Then I guess maybe remove the `.haxelib` folder from your source code folder? I have never really experienced this kind of issue before.
> > > > 
> > > > 
> > > > (secondary account) bro i will delete the entire library if i do that
> > > 
> > > 
> > > just run the update.bat again after deleting it, it won’t delete your global haxelibs, it’ll only delete the local ones you stupid bastard
> > 
> > 
> > i knooow, I was talking about the engine library
> 
> it’ll just make a new one when you run update.bat, it’s not even hard to make you just run haxelib newrepo, the engine library isn’t even a thing wtf do you mean? like just delete the .haxelib folder and run the update.bat again

I know what you mean and I repeat, I have done it many times. I know what I'm doing, what I don't know is WHY THE LIME DOESN'T DOWNLOAD AS IT SHOULD.

**Comment by FacunMax** [comment]
okay I tried everything and there seems to be no way to solve it. The only way there is, is to ask someone for his lime (which I did and that's why I can compile now)
thanks peppy
