### ISSUE TITLE
Missing liblvc file for Linux target?

### ISSUE THREAD

**Issue by Stefan2008Git** [FNF-CNE-Devs/CodenameEngine#262]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)

[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ x] Linux
[ ] Mac

### Explain your issue
Does libvlc file missing or the build it's not completely compiled?
![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/126715034/baa2c950-e5b4-48e7-a3cc-bde7f192e97c)
##### Please check first if your issue haven't already been reported yet.
Nope. This is my first time using CNE

[weed]: <> ()

**Comment by 2Schoolhouse** [comment]
This is likely that you don't have `libvlc-dev` installed on your computer. If so, then you'll have to install the `libvlc-dev` package, using Pop-OS's package installation command. I myself don't use Pop-OS, but when troubleshooting this through Ubuntu, I got the same error, so I just installed the `libvlc-dev` package.

**Comment by Stefan2008Git** [comment]
> This is likely that you don't have `libvlc-dev` installed on your computer. If so, then you'll have to install the `libvlc-dev` package, using Pop-OS's package installation command. I myself don't use Pop-OS, but when troubleshooting this through Ubuntu, I got the same error, so I just installed the `libvlc-dev` package.

I actually downloaded the fresh build from latest actions workflow. Didn't compiled the game

**Comment by 2Schoolhouse** [comment]
> I actually downloaded the fresh build from latest actions workflow. Didn't compiled the game

Ah. You might still need the package, though, since the game still needs the usage of it.

**Comment by Stefan2008Git** [comment]
> > I actually downloaded the fresh build from latest actions workflow. Didn't compiled the game
> 
> Ah. You might still need the package, though, since the game still needs the usage of it. Specifically, as far as I'm aware, it is used for MP4s.

I will try. Hold on, just give me the time

**Comment by Stefan2008Git** [comment]
Sorry for lately respond @PetscopF. It works now since i switched to different distro

**Comment by PetscopF** [comment]
> Sorry for lately respond @PetscopF. It works now since i switched to different distro

It's alright. I myself do tend to use Arch, which I do know has the package, but a package repository lacking the libVLC package is something that I believe can happen at times.

**Comment by Stefan2008Git** [comment]
> > Sorry for lately respond @PetscopF. It works now since i switched to different distro
> 
> It's alright. I myself do tend to use Arch, which I do know has the package, but a package repository lacking the libVLC package is something that I believe can happen at times.

I am using Manjaro, so that's why
