### ISSUE TITLE
Bug Report: [RESET SAVE DATA not doing anything]

### ISSUE THREAD

**Issue by Jammington24** [FNF-CNE-Devs/CodenameEngine#263]
### Which target are you using?

[x] Windows
[ ] Linux
[ ] Mac

### Explain your issue
In the v.s Gorefield V2 mod I tried the option RESET SAVE DATA, but when I checked Freeplay, all my highscores remained intact. I don't know if I have to do something with the cache, or my laptop is preventing the mod from deleting its own data, or if it's the engine itself. I tried the option several times, and not even the changes I did on Chart Editor were reset.

**Comment by CharlesCatYT** [comment]
the reset save data function wasnt implemented actually, only the option itself was intact, do you really have to fall for that?

**Comment by Jammington24** [comment]
It's nothing urgent; I just thought it would be easier to figure out my custom code if I beat the full mod in the same day. Thank you.
