### ISSUE TITLE
You made the dev branch public on accident?

### ISSUE THREAD

**Issue by biomseed** [FNF-CNE-Devs/CodenameEngine#264]
![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/73907153/c01698f9-8b9c-4f80-9809-a2ccbb03a89a)

**Comment by NeeEoo** [comment]
It was for a prank lol

**Comment by NexIsDumb** [comment]
LMFAO THE PRANK WENT SO WRONG😭
