### ISSUE TITLE
Compiling help: Haxe 4.3.4 with Latest Flixel Issue

### ISSUE THREAD

**Issue by mcagabe19** [FNF-CNE-Devs/CodenameEngine#265]
### Which target are you using?

[x] Windows
[] Linux
[] Mac

### Explain your issue
![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/82843871/eb93a201-e680-4917-82c0-333b50d822f9)

#### haxelib list
![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/82843871/3b6ba92f-cd52-4a7c-97f5-fba1db9dda46)

**Comment by NexIsDumb** [comment]
hmm, does this still happen with haxe 4.2.5?

**Comment by mcagabe19** [comment]
> hmm, does this still happen if you change haxe to 4.2.5?

nope

**Comment by NexIsDumb** [comment]
> > hmm, does this still happen if you change haxe to 4.2.5?
> 
> 
> 
> nope, 4.2.5 is fine

oh then for now I recommend you to use 4.2.5, as we said in the compiler warning, compiling 4.3.x isn't still fully supported
although stay assure that in the future we intend to only use 4.3.1 and beyond

**Comment by NeeEoo** [comment]
@mcagabe19 Run update.bat

**Comment by mcagabe19** [comment]
> @mcagabe19 Run update.bat

no change still same errors
