### ISSUE TITLE
Bug Report: [I CAN'T OPEN THE FREE PLAY ]

### ISSUE THREAD

**Issue by Hola234tobotos** [FNF-CNE-Devs/CodenameEngine#274]
[ ] android

**Comment by NexIsDumb** [comment]
cne doesnt officially support android, we only set some stuff to make it easier for the porters

**Comment by Hola234tobotos** [comment]
thanks but wait for them to solve it

**Comment by NexIsDumb** [comment]
> thanks but wait for them to solve it 

them who?

**Comment by Hola234tobotos** [comment]
-_-

**Comment by NexIsDumb** [comment]
> -_- 

??
if you mean the cne's devs im one of them
