### ISSUE TITLE
Compiling help: Can't find VsDevCmd

### ISSUE THREAD

**Issue by mykmeik2007** [FNF-CNE-Devs/CodenameEngine#277]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### It couldn't find Visual Studio VsDevCmd. I installed everything that was in README.
![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/99096012/ae835be9-b3b7-4b3e-b5ad-d020f70cd77a)

**Comment by 2Schoolhouse** [comment]
It's recommended to use Haxe 4.2.5 rather than 4.3.0 for Codename, so I'd probably suggest changing the Haxe version to that first.
