### ISSUE TITLE
Bug Report: custom alphabet doesn't reload

### ISSUE THREAD

**Issue by what-is-a-git** [FNF-CNE-Devs/CodenameEngine#284]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

### Explain your issue

basically when you use a custom data/alphabet.xml it doesn't get reloaded when loading into other mods, causing some strange behavior if you use differently named animations

![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/138817584/f4da314b-0419-4c01-94a5-f08e706e4d0a)

also fun fact: you can crash the game if you rename the custom alphabet from alphabet.xml to something else and load into another mod

![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/138817584/8d7e9225-fc17-42b7-b694-ffa7b58d07a7)

**Comment by usb-port-2** [comment]
"you can crash the game if you rename the custom alphabet from alphabet.xml to something else and load into another mod"
no shit dumbass it needs that to run the game

if i delete system32 it isn't window's fault my pc doesn't work, it's mine because i was being a dumbass

**Comment by moxie-coder** [comment]
> "you can crash the game if you rename the custom alphabet from alphabet.xml to something else and load into another mod" no shit dumbass it needs that to run the game
> 
> if i delete system32 it isn't window's fault my pc doesn't work, it's mine because i was being a dumbass

Ikr

**Comment by usb-port-2** [comment]
"causing some strange behavior if you use differently named animations"
No fucking way, using something incorrectly does something wrong? I had no idea! I will tell the codename engine devs to cancel the entire thing and delete the repository.

This isn't an issue with the engine, dude.

**Comment by what-is-a-git** [comment]
it seems my original post may have not been that clear on what the issue i'm talking about really is so i'm making this comment to clarify

the issue was never about data/alphabet.xml not working, it works as you'd expect, allowing you to add, change, and remove different animations in alphabet text.

the issues arise with the specific fact that if you were to put a custom data/alphabet.xml in a mod, and then load into another mod or the base game, the data is not reloaded, so things can get glitchy and not work as expected

the first screenshot shows this in the case that if you use differently named animations in your custom data/alphabet.xml, but the same spritesheet path, then the game won't crash in other mods, but will instead display characters incorrectly. 

this is expected behavior of the bug however, as the sprites were reloaded, but not the data, causing a desync between data/alphabet.xml and the actual sprites in use

the second screenshot seems to have been heavily misinterpreted so here's a better explanation:

when you change the spritesheet path property in data/alphabet.xml and you're in the same mod as that data/alphabet.xml, everything works as intended and your different spritesheet is used over the base one and path.

the crash occurs when you are using this different path, and then load into a different mod. this causes a crash because the game is still using the same path from a previous mod (that, as expected, no longer exists), and it provides no fallback for this situation

the reason i made an issue about this is because it seems to be unintended behavior, as, if you let the user use a mod to customize the functionality of alphabet text, it would be expected to reload depending on what mod you're playing (assuming a mod has a custom one or doesn't), allowing a more seamless and customizable experience that wouldn't crash or have any conflicts between mods
