### ISSUE TITLE
Bug Report: [DESCRIBE YOUR BUG IN DETAIL HERE]

### ISSUE THREAD

**Issue by bmaniac68** [FNF-CNE-Devs/CodenameEngine#304]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### wth do i do?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

![Screenshot 2024-05-27 092224](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/157898657/83bba46d-be53-467c-8846-7e6967c21145)
[x] Windows
[ ] Linux
[ ] Mac

##### 
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by 2Schoolhouse** [comment]
Refer to issue #291.
