### ISSUE TITLE
Compiling help: Everytime i try and open CNE it just says ''process creation failure : attrib +h.temp.''

### ISSUE THREAD

**Issue by samiguesss** [FNF-CNE-Devs/CodenameEngine#309]
### Which target are you using?

[x] Windows
[ ] Linux
[ ] Mac

### Not sure if this is a ''bug'' or a ''compiling help'' but im PRETTY SURE its a ''compiling help'' so here's the case.
 
I have no idea why but every single time i try to open CNE it just display this error message, i've practically tried everything, **change versions,** **looking in the files** and tried anything to fix it. But what is strange is that the first time i downloaded and tested the engine it worked perfectly, but when i tried adding a mod into the mod folder it just broke completely and this error appears everytime. 

![imagem_2024-06-01_230614331](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/171460818/3b66e79d-2e1f-43b2-ba0e-740297c48b50)

**Comment by NexIsDumb** [comment]
#291
