### ISSUE TITLE
Compiling help: [Haxelib Problems / HScript Problems]

### ISSUE THREAD

**Issue by TechDevOfficial** [FNF-CNE-Devs/CodenameEngine#314]
Hello, i'm getting these errors with compiling the last source code file branch main. How to fix?

[ x ] Windows
[ ] Linux
[ ] Mac

![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/89547375/cc6b1e79-3b72-4d35-bf50-83e24a1a41db)

**Comment by TechDevOfficial** [comment]
Update.bat crash after installing hxdiscord_rpc

**Comment by PetscopF** [comment]
> Hello, i'm getting these errors with compiling the last source code file branch main. How to fix?
> 
> [ x ] Windows [ ] Linux [ ] Mac
> 
> ![image](https://private-user-images.githubusercontent.com/89547375/338230572-cc6b1e79-3b72-4d35-bf50-83e24a1a41db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNDQ4NjgsIm5iZiI6MTcxODE0NDU2OCwicGF0aCI6Ii84OTU0NzM3NS8zMzgyMzA1NzItY2M2YjFlNzktM2I3Mi00ZDM1LWJmNTAtODNlMjRhMWE0MWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDIyMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YjgzMDE0MTVmMGZkNzZhMzk1Y2ExMjM5YTFkOGVkNGI2NmQ5NGU1OTYyMjcyNGJhM2Q0YThlYWFmMDM4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.shm-KNJ_P-B7w6QW67PiR8OQuW8o7u8rxFOySM90iNo)

For the very last one, go to `MusicBeatState.hx`, then line 124. Make sure to add a parenthesis symbol wherever needed.

As for the rest, it might have to do with the macros. I'm not exactly sure _what,_ since I don't use macros usually, however.

> Update.bat crash after installing hxdiscord_rpc

Are you sure you have [`git-scm`](https://www.git-scm.com/downloads) installed on your system? It is a possibility that you might not have it.

**Comment by NexIsDumb** [comment]
yeah that actually happens cause you gotta update the hscript improved library

**Comment by NeeEoo** [comment]
Update to 4.2.5

**Comment by NexIsDumb** [comment]
(closing this since no answers for a while, feel free to reopen if you need

**Comment by TechDevOfficial** [comment]
Hello, sorry if i didn't answer.. I have latest haxe ver, latest hscript improved ver, and latest git ver, so it is not git
