### ISSUE TITLE
Enhancement: Make week 6 dialog (and maybe enhance it)

### ISSUE THREAD

**Issue by IdkWhatAmIDoin** [FNF-CNE-Devs/CodenameEngine#316]
## What is your suggestion, and why should it be implemented?
I want the week 6 dialog. I can see why the devs cant do this because week 6's dialog is stored in txt, but you can make a json dialogue and add a "pixelated=true/false" setting. For the spirit dialog, you can make a setting called "scary=true/false". You can enhance it many ways, such as making it more decorated, and making it longer like the current dialogue.

**Comment by IdkWhatAmIDoin** [comment]
wait

**Comment by IdkWhatAmIDoin** [comment]
it was already there wasnt it

**Comment by NexIsDumb** [comment]
yuuup, i added it a while ago, around january
