### ISSUE TITLE
Bug Report: Week 6 dialogue, background EXTREMELY zoomed out

### ISSUE THREAD

**Issue by IdkWhatAmIDoin** [FNF-CNE-Devs/CodenameEngine#317]
### Which target are you using?

- [x] Windows

##### Please check first if your issue haven't already been reported yet.
Alright, so i just launched the game and why the heck does the week 6 dialogue be *that* zoomed out? Look at this. LOOK AT THIS. 
![this is the this](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/171820170/82a224ed-d5e6-4295-b57e-9164c81465d1). Why is it so, zoomed out?
*please fix this.*

**Comment by NexIsDumb** [comment]
uhhh, its not like that to me actually

**Comment by PetscopF** [comment]
> ### Which target are you using?
> * [x]  Windows
> 
> ### Explain your issue
> ##### Please check first if your issue haven't already been reported yet.
> Alright, so i just launched the game and why the heck does the week 6 dialogue be _that_ zoomed out? Look at this. LOOK AT THIS. ![this is the this](https://private-user-images.githubusercontent.com/171820170/338267529-82a224ed-d5e6-4295-b57e-9164c81465d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNDU0NDQsIm5iZiI6MTcxODE0NTE0NCwicGF0aCI6Ii8xNzE4MjAxNzAvMzM4MjY3NTI5LTgyYTIyNGVkLWQ1ZTYtNDI5NS1iNTdlLTkxNjRjODE0NjVkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQyMjMyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmRjZDJjY2Y3NmJhNTIyNzEwODg2OWJiNTI3ZWEyMTQyZDAwMWE3ZjdkMjQ5YzQ5N2JkODRlN2EwNjg3MWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mf1OX64FL3lVrj8Pc4eDV9q9-6VbqPFeXfdV7C_asfc). Why is it so, zoomed out? _please fix this._

I _think_ `camGame` is just THAT zoomed out when loading it in? This is kind of an anomaly if you didn't even modify the code.

**Comment by NexIsDumb** [comment]
> > ### Which target are you using?
> > * [x]  Windows
> > 
> > ### Explain your issue
> > ##### Please check first if your issue haven't already been reported yet.
> > Alright, so i just launched the game and why the heck does the week 6 dialogue be _that_ zoomed out? Look at this. LOOK AT THIS. ![this is the this](https://private-user-images.githubusercontent.com/171820170/338267529-82a224ed-d5e6-4295-b57e-9164c81465d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNDU0NDQsIm5iZiI6MTcxODE0NTE0NCwicGF0aCI6Ii8xNzE4MjAxNzAvMzM4MjY3NTI5LTgyYTIyNGVkLWQ1ZTYtNDI5NS1iNTdlLTkxNjRjODE0NjVkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQyMjMyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmRjZDJjY2Y3NmJhNTIyNzEwODg2OWJiNTI3ZWEyMTQyZDAwMWE3ZjdkMjQ5YzQ5N2JkODRlN2EwNjg3MWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mf1OX64FL3lVrj8Pc4eDV9q9-6VbqPFeXfdV7C_asfc). Why is it so, zoomed out? _please fix this._
> 
> I _think_ `camGame` is just THAT zoomed out when loading it in? This is kind of an anomaly if you didn't even modify the code.

oh really??? i'll def check the code then

**Comment by NexIsDumb** [comment]
false allarm i guess?

![image](https://github.com/user-attachments/assets/c085c512-f5b9-4e71-b389-b8a94eb61198)

**Comment by NexIsDumb** [comment]
i think it was due to the flxcameras being inactive, that was fixed later with aburridow's pr

**Comment by NexIsDumb** [comment]
okay nvm found the issue, it only happens if you have pixel perfect enabled
