### ISSUE TITLE
how do i move character, is there any script/event to do that?

### ISSUE THREAD

**Issue by Fawaazmh1** [FNF-CNE-Devs/CodenameEngine#319]
help me if ya'll know

**Comment by NexIsDumb** [comment]
move in what way? like you want just to adjust its position in the stage in the whole song or after a specific time in the song its position changes?

**Comment by PetscopF** [comment]
> help me if ya'll know

If you mean simply setting the character position, you can try and change the specific character's `x` or `y` variable like a variable.

**Comment by NexIsDumb** [comment]
(closing this since no answers for a while, feel free to reopen if you need

**Comment by A-15iscool** [comment]
I also wanted to move the character mid-song, Isnt there like an event for it to do that? Like gliding to x and y? I was about to chart Bambi's mukbang

**Comment by r6915ee** [comment]
> I also wanted to move the character mid-song, Isnt there like an event for it to do that? Like gliding to x and y? I was about to chart Bambi's mukbang

Gliding can be done using [tweens](https://api.haxeflixel.com/flixel/tweens/FlxTween.html).
