### ISSUE TITLE
Missing flixel library flixel even tho it's installed

### ISSUE THREAD

**Issue by Arolox666** [FNF-CNE-Devs/CodenameEngine#322]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
I wanted to compile the engine and I got an error "Cannot process [flixel]: Library flixel is not installed : run 'haxelib install flixel'" even tho it's installed and I even reinstalled the library and still nothing. I know it's problem of the source code as game I'm making works correctly

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x ] Windows
[ ] Linux
[ ] Mac

![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/168214112/5dfe6f2f-26b0-4fcf-b066-0b516f80734c)

**Comment by PetscopF** [comment]
> I wanted to compile the engine and I got an error "Cannot process [flixel]: Library flixel is not installed : run 'haxelib install flixel'" even tho it's installed and I even reinstalled the library and still nothing. I know it's problem of the source code as game I'm making works correctly
> 
> ### Which target are you using?
> [x ] Windows [ ] Linux [ ] Mac
> 
> ![image](https://private-user-images.githubusercontent.com/168214112/342101111-5dfe6f2f-26b0-4fcf-b066-0b516f80734c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjg5MjgsIm5iZiI6MTcxOTE2ODYyOCwicGF0aCI6Ii8xNjgyMTQxMTIvMzQyMTAxMTExLTVkZmU2ZjJmLTI2YjAtNGZjZi1iMDY2LTBiNTE2ZjgwNzM0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxODUwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2VmYzczNjUwMzQ0YTcyZGU4OTYyMzhiYzFkMGQxNDA1NmY3NDdjZTNiZjUwZTRmZTAyODRlZGQzMTgwNDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.StktYviMwwZsskq1UpMWMpYGR2FWP0pboGqgiJQ7an8)

Did you run the `update.bat` file in the repository's root folder?

**Comment by NexIsDumb** [comment]
(closing this since no answers for a while, feel free to reopen if you need
