### ISSUE TITLE
Compiling help: i need help with this error

### ISSUE THREAD

**Issue by adamgamer12333** [FNF-CNE-Devs/CodenameEngine#325]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
##### Please check first if your issue haven't already been reported yet, and make sure you ran the `update.bat` file before building.

source/funkin/game/PlayState.hx:20: characters 25-27 : Expected ) or , or :

**Comment by NexIsDumb** [comment]
what did you edit in the source, since it has to be because of that

**Comment by adamgamer12333** [comment]
> what did you edit in the source, since it has to be because of that

![screenshot of error](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/158506937/711883a7-04ea-4244-bf8b-8dfdb46fb4d8)

**Comment by NexIsDumb** [comment]
> > what did you edit in the source, since it has to be because of that
> 
> ![screenshot of error](https://private-user-images.githubusercontent.com/158506937/342496100-711883a7-04ea-4244-bf8b-8dfdb46fb4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNjUzNDksIm5iZiI6MTcxOTI2NTA0OSwicGF0aCI6Ii8xNTg1MDY5MzcvMzQyNDk2MTAwLTcxMTg4M2E3LTA0ZWEtNDI0NC1iZjhiLThkZmRiNDZmYjRkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQyMTM3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmMwNjBjMmIxY2JlYmQwYzRkODRiYTk3NDc4MjJiYzE1YzZhZDZiYzExNGY3NjUxOTU3OWU5MWFiNTM3ODQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UWpWYOjM0TaBwoV-OaN7H9fuLvYfFH5F2jqQxHOB6e8)

you can't for sure do that in haxe
for helping you though i need more context of what were you trying to do

**Comment by NexIsDumb** [comment]
(closing this since no response back from a while
