### ISSUE TITLE
How do i disable the popup blur?

### ISSUE THREAD

**Issue by mateus683** [FNF-CNE-Devs/CodenameEngine#331]
I always lag when a popup comes in and i think it is because of the blur that it leaves on the back. How can i remove it?

**Comment by NexIsDumb** [comment]
theres an option for it when you press 7 in the main menu -> debug options iirc, or just check the normal options

**Comment by mateus683** [comment]
> theres an option for it when you press 7 in the main menu -> debug options iirc, or just check the normal options

K then
