### ISSUE TITLE
How to make video below hud?

### ISSUE THREAD

**Issue by Remkich** [FNF-CNE-Devs/CodenameEngine#335]
I wanna put video below hud, how to do it?

**Comment by NexIsDumb** [comment]
> I mean, Codename uses hxvlc for its videos. Theoretically, you should be able to add an FlxVideoSprite as usual, then set its camera to `camHUD`, THEN add it as you normally would with a regular FlxSprite.

exactly, treat the video as a sprite once you use the flxvideosprite class

**Comment by NexIsDumb** [comment]
(imma close this since it has been a while from the last response
