### ISSUE TITLE
Tankman spritesheet is not properly centered 

### ISSUE THREAD

**Issue by SabDoesStuff** [FNF-CNE-Devs/CodenameEngine#338]
### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x ] Windows
[ ] Linux
[ ] Mac

So, I was playing through the base game again, and then I came across week 7. Everything was fine until I looked at tankmans notes and noticed... His spritesheet was not perfectly centered. His feet shift and slide across the sand when he hits the right note (I think)
To approach this bug, click on week 7 (I found this bug on guns) and take a look at his feet (Not in a weird way) (Unless you freaky like that, no shame)

**Comment by NexIsDumb** [comment]
we kinda left that on purpose to give og game's vibes
