### ISSUE TITLE
Request for Collaboration/Question about your project

### ISSUE THREAD

**Issue by expertyeti** [FNF-CNE-Devs/CodenameEngine#345]
Hello developers of CodeNameEngine,

I hope this message finds you well. My name is Britex, and I am interested in collaborating with you on the CodeNameEngine project. I am very impressed with your work and would like to ask you some questions and explore potential collaboration opportunities.

Could we connect via email or another preferred method of communication?

Best regards,
Britex

**Comment by moxie-coder** [comment]
looking at your profile, I can safely say that you’re full of shit, and you should know your place, and your place is **nothing**

**Comment by expertyeti** [comment]
Upon closer inspection, I appreciate your attention. This profile I have is secondary, and I cannot definitively say whether my place is among the greats or simply nonexistent. What I do know is that it's something beyond your current perception.

**Comment by moxie-coder** [comment]
> Upon closer inspection, I appreciate your attention. This profile I have is secondary, and I cannot definitively say whether my place is among the greats or simply nonexistent. What I do know is that it's something beyond your current perception.

I don’t think FNF is the place you should be in, go back to your own html coding shit

**Comment by moxie-coder** [comment]
> Upon closer inspection, I appreciate your attention. This profile I have is secondary, and I cannot definitively say whether my place is among the greats or simply nonexistent. What I do know is that it's something beyond your current perception.

let me put this in a more better way, why would the devs want to hire someone like you who they don't even know? plus your profile really is lacking and makes me think you're just a scammer and someone who can't be trusted, I don't know you, you don't look like someone in the FNF community, I don't trust you and I have good reasons and beliefs for that

**Comment by moxie-coder** [comment]
and plus, if this is "your secondary", why not come here on your main then?

**Comment by expertyeti** [comment]
**Hi Moxie**,

I would like to clarify that the attitude you showed yesterday seemed unprofessional and non-assertive to me. For this reason, I am not willing to work with developers who lack credibility in terms of social relations. I understand your concern in thinking that I might be a scammer; however, this account was created primarily to avoid any conflicts that could tarnish my image. I am not aggressive nor do I do anything that could compromise me, although I have had experiences where others have tried to make me look bad. :/

**I am an active member of the FNF community.** I participate in Reddit groups, follow posts from the original engine developers, and watch Phandom Arcade streams whenever I can to stay up to date. I am also a small but active content creator, and I have been part of this community for about four years.

I came here because I saw a lot of potential in this engine. I observed various opportunities to significantly optimize it without affecting the player's experience. My intention was to help reduce and/or eliminate unnecessary code, create a lite version for low-end PCs, in addition to the standard version with more functionalities and optimizations. I also thought about better control of the libraries, which by the way, are well-structured, and I must acknowledge that. I even considered making a mobile port.

However, after talking with you, Moxie, I must say that I am not comfortable working in a social development environment like the one I experienced with you. Thank you for your attention :b.

**Comment by moxie-coder** [comment]
> **Hi Moxie**,
> 
> I would like to clarify that the attitude you showed yesterday seemed unprofessional and non-assertive to me. For this reason, I am not willing to work with developers who lack credibility in terms of social relations. I understand your concern in thinking that I might be a scammer; however, this account was created primarily to avoid any conflicts that could tarnish my image. I am not aggressive nor do I do anything that could compromise me, although I have had experiences where others have tried to make me look bad. :/
> 
> **I am an active member of the FNF community.** I participate in Reddit groups, follow posts from the original engine developers, and watch Phandom Arcade streams whenever I can to stay up to date. I am also a small but active content creator, and I have been part of this community for about four years.
> 
> I came here because I saw a lot of potential in this engine. I observed various opportunities to significantly optimize it without affecting the player's experience. My intention was to help reduce and/or eliminate unnecessary code, create a lite version for low-end PCs, in addition to the standard version with more functionalities and optimizations. I also thought about better control of the libraries, which by the way, are well-structured, and I must acknowledge that. I even considered making a mobile port.
> 
> However, after talking with you, Moxie, I must say that I am not comfortable working in a social development environment like the one I experienced with you. Thank you for your attention :b.

1. I can be professional, but when it comes to stuff outside of professional stuff, I don't act like that because it's not the kind of person I am, you're acting like this is a fucking professional job when it's literally just some online FNF coders who wanted to make an engine for the sake of making an engine that's actually good

2. I don't see you around making contributions to the game do I? if you really are I wanna see proof of that shit

3. I'm glad you do but it's already optimized as much as possible, Neo, Lunar, and Nex obviously know what they're doing and so does Yoshicrafter (who left the fnf community a long time ago but still), and Neo has made this engine as optimized as it can be, it already can run just fine and I don't see any other way of making this optimized as possible, and there's already an GPU Caching option so you can use that if you have a good GPU, otherwise I don't see how it's possible, and also there's already an mobile port me and some friends we're making

> However, after talking with you, Moxie, I must say that I am not comfortable working in a social development environment like the one I experienced with you

then go to an actual professional fucking area, instead of just yapping your fucking face off here, get an actual job, work in actual professional fucking areas, it's a community of FNF Modders, not an professional part time job you fucking dingus, go to an actual work place if you think that, instead of just yapping here like fucking hell, FNF community is full of minors and some of the people who've worked on this engine (Nex and Yoshicrafter who are minors) are goddamn minors, what the fuck do you think this is you goddamn idiot

**Comment by moxie-coder** [comment]
I know people have been paid to work on FNF mods before, but it's not like it's an actual job, which it really isn't because there's no actual, level of *professionalism*

**Comment by expertyeti** [comment]
I truly didn't think that professionalism and formality would frustrate you so much. I am a minor and not looking for a job; I genuinely love this community and want to contribute. Honestly, you disgust me. You are likely older than me, but I probably know more things than you do. But this isn't about that. What are you trying to achieve by responding to me if you've already 'made yourself clear'?  Your way of speaking and lack of assertiveness repulses me.

I was only looking for an opportunity to contribute something more. And yes, even if you find it hard to believe, the engine can still be optimized further. The mobile port isn't a big deal; I already created one thinking I could really join. But let me emphasize, I don't plan to work with people like you. You give a bad impression, you know? I really appreciate you wasting your time on this crap.

:]

**Comment by expertyeti** [comment]
I really don't intend to show you anything when I'm not willing to work with you.

**Comment by moxie-coder** [comment]
> > **I am an active member of the FNF community.** I participate in Reddit groups, follow posts from the original engine developers, and watch Phandom Arcade streams whenever I can to stay up to date. I am also a small but active content creator, and I have been part of this community for about four years.
> > I came here because I saw a lot of potential in this engine. I observed various opportunities to significantly optimize it without affecting the player's experience. My intention was to help reduce and/or eliminate unnecessary code, create a lite version for low-end PCs, in addition to the standard version with more functionalities and optimizations. I also thought about better control of the libraries, which by the way, are well-structured, and I must acknowledge that. I even considered making a mobile port.
> 2. I don't see you around making contributions to the game do I? if you really are I wanna see proof of that shit

I wanna go back on point two, you literally did not answer my question on why you just didn't come on your main, if this was your second account, and never brought up anything about the Haxe stuff or anything like that, like you have some weird ass repos on your profile, like what the hell are they even supposed to be?


> I really don't intend to show you anything when I'm not willing to work with you.

then I don't trust you and just believe you're full of shit you know that? you're like an actual person who's just deceptive, you also have nothing on your profile, and I'm beginning to doubt this is even your secondary at all if you're simply not gonna show anything, you acting like this is only making me believe you have no good intentions at all, I only made that comment about you in the first place because you're profile is suspicious as hell, and here you go doing stupid shit like this

**Comment by moxie-coder** [comment]
> I truly didn't think that professionalism and formality would frustrate you so much. I am a minor and not looking for a job; I genuinely love this community and want to contribute. Honestly, you disgust me. You are likely older than me, but I probably know more things than you do. But this isn't about that. What are you trying to achieve by responding to me if you've already 'made yourself clear'? Your way of speaking and lack of assertiveness repulses me.
> 
> I was only looking for an opportunity to contribute something more. And yes, even if you find it hard to believe, the engine can still be optimized further. The mobile port isn't a big deal; I already created one thinking I could really join. But let me emphasize, I don't plan to work with people like you. You give a bad impression, you know? I really appreciate you wasting your time on this crap.
> 
> :]

yeah because it's like you don't actually have one, if you're not showing me shit, then I doubt you even have something to show in the first place

**Comment by moxie-coder** [comment]
and also it's not the professional or anything that frustrates me, it's *you* that frustrates me because you're acting like an suspicious piece of shit rn not wanting to show anything, and having a suspiciously weird profile

**Comment by moxie-coder** [comment]
but if you wanna keep yapping your head off then we can keep going down that path, otherwise go fuck off and do something in your life you actual retard

**Comment by expertyeti** [comment]
I really don't care now, thank you again for your damn waste of time. Just a simple "you can't work because your account is suspicious" is more than enough. You don't even know me and you're talking shit about me. To begin with, talking is easy. You think I'm lying, but I'm not, and I believe that people like you don't deserve a real place. I won't continue with this damn totally unnecessary conversation. You really complicate things. I thank you for your shitty attention. Goodbye.

**Comment by moxie-coder** [comment]
> I really don't care now, thank you again for your damn waste of time. Just a simple "you can't work because your account is suspicious" is more than enough. You don't even know me and you're talking shit about me. To begin with, talking is easy. You think I'm lying, but I'm not, and I believe that people like you don't deserve a real place. I won't continue with this damn totally unnecessary conversation. You really complicate things. I thank you for your shitty attention. Goodbye.

talking is easy? it’s not fucking easy on text to know when you’re lying or not, alright you know what just GET THE FUCK OUT, **GET THE FUCK OUT**

https://github.com/user-attachments/assets/9ab9b76c-a9bd-4dea-8844-67549757bc07

**Comment by expertyeti** [comment]
hahaha, realmente me da risa, hermano, espero que el engine siga bien, quizas en un futuro volvere pero con mi cuenta principla, ahora mismo estoy pasando por una situacion desagradable con esa cuenta gracias a unas cuantas personas que me hicieron quedar mal con mi comunidad y realmente tienen las antorchas levantadas, esperare a que se relaje la marea para pocer ver si puedo entrar al equipo de desarrollo, hasta entonces trabajare en mejorar este perfil y el principal, hasta luego hermano :)

Hahaha, it really makes me laugh, brother. I hope the engine is doing well. Maybe in the future, I’ll come back with my main account. Right now, I'm going through an unpleasant situation with that account because of a few people who made me look bad with my community, and they really have their torches raised. I’ll wait for the tide to calm down to see if I can join the development team. Until then, I’ll work on improving this profile and the main one. See you later, brother :)

**Comment by moxie-coder** [comment]
> hahaha, realmente me da risa, hermano, espero que el engine siga bien, quizas en un futuro volvere pero con mi cuenta principla, ahora mismo estoy pasando por una situacion desagradable con esa cuenta gracias a unas cuantas personas que me hicieron quedar mal con mi comunidad y realmente tienen las antorchas levantadas, esperare a que se relaje la marea para pocer ver si puedo entrar al equipo de desarrollo, hasta entonces trabajare en mejorar este perfil y el principal, hasta luego hermano :)
> 
> Hahaha, it really makes me laugh, brother. I hope the engine is doing well. Maybe in the future, I’ll come back with my main account. Right now, I'm going through an unpleasant situation with that account because of a few people who made me look bad with my community, and they really have their torches raised. I’ll wait for the tide to calm down to see if I can join the development team. Until then, I’ll work on improving this profile and the main one. See you later, brother :)

I tried to be reasonable here, I already told you once before that you looked too suspicious because your account literally looked suspicious, then you decided to pull some crap on me when I tried to make an point to you, and again, you still haven't proved any of them, like it only takes a minute to switch accounts and you still haven't bothered to do that, nor even showed any proof of it, you know what just fuck you man, just fuck you, vete a la mierda gilipollas, can't bother to even send a screenshot of it too penjedo

**Comment by expertyeti** [comment]
hehe

**Comment by moxie-coder** [comment]
and plus, if you didn't care, you wouldn't keep replying

**Comment by expertyeti** [comment]
meh, you were right about some things but not others :u, I really don't want to argue, just talk and you keep giving me your time

**Comment by moxie-coder** [comment]
> meh, you were right about some things but not others :u, I really don't want to argue, just talk and you keep giving me your time

then this is what I mean by you being an piece of shit, all I think right now is you’re some troll on the internet who thought he could get away with being an liar, like they literally have discord, there’s fucking PRs you could’ve just fucking done instead of this shit

**Comment by NexIsDumb** [comment]
im saving this whole conversation somewhere istfg😭😭

**Comment by usb-port-2** [comment]
Average day in the fnf coding community

**Comment by NeeEoo** [comment]
Hello Britex aka @expertyeti, formerly known as javirjolin. I'm sorry, but i don't think we could accept you yet, because we don't know what skills you have, since your Github profile is very empty.

**Comment by Itzbeepi77** [comment]
Uhh wtf

**Comment by usb-port-2** [comment]
Erm... what the sigma?!

**Comment by LeonGamerPS1** [comment]
errrm, what the 494kd on discord

**Comment by moxie-coder** [comment]
> Hello Britex aka @expertyeti, formerly known as javirjolin. I'm sorry, but i don't think we could accept you yet, because we don't know what skills you have, since your Github profile is very empty.

to be honest this was what I was trying to say in the first place, and it came across as rude because of how things have changed over the years, so I wanna try be less of that, and more of this, which is less rude because I do wanna try to be helpful, if that makes sense

**Comment by Itzbeepi77** [comment]
Uhh..

**Comment by PetscopF** [comment]
This whole conversation is certainly something that could've just been solved with a pull request.

**Comment by moxie-coder** [comment]
> This whole conversation is certainly something that could've just been solved with a pull request.

yeah that’s what I said earlier, it would’ve been much more better tbh

**Comment by expertyeti** [comment]
LOL

**Comment by ItsBritex** [comment]
Hermano es realmente "LMAO" hacia los devs wtf

**Comment by expertyeti** [comment]
> > Toda esta conversación es ciertamente algo que podría resolverse con una solicitud de extracción.
> 
> Sí, eso es lo que dije antes. Habría sido mucho mejor, sinceramente.

Send me your discord, I want to talk to you privately (md)

**Comment by LeonGamerPS1** [comment]
womp womp @youtube

**Comment by yahyamodder** [comment]
whoremembers

**Comment by NovaAshwolfDev** [comment]
HEY I WAS JUST LOOKING HERE

**Comment by chronicsilly** [comment]
ancient codename faps

**Comment by imbritex** [comment]
> ancient codename faps

But-

**Comment by NovaAshwolfDev** [comment]
> ancient codename faps

prehistoric even

**Comment by imbritex** [comment]
> > ancient codename faps
> 
> prehistoric even

But let this die already, lmfaooo
