### ISSUE TITLE
Enhancement: Chart playtesting and pressing escape when in game over

### ISSUE THREAD

**Issue by willerisreal123** [FNF-CNE-Devs/CodenameEngine#351]
## What is your suggestion, and why should it be implemented?

i feel like making it so that you return to the chart editor when you press escape on the game over screen is a needed addition, since
i just tried to do that and it just made me return to freeplay, i'm not sure if i just lost progress or not

**Comment by NexIsDumb** [comment]
oh shit if thats true thats actually a bug

**Comment by NexIsDumb** [comment]
yep confirmed, give me a sec

**Comment by NexIsDumb** [comment]
wait its actually not  abug dont worry!
it makes you go to freeplay if you didnt edit anything, but if you did, it gives you a warning; so you're covered!

![image](https://github.com/user-attachments/assets/f1bfac53-9ae3-4793-9b5b-26ac01c2daef)
