### ISSUE TITLE
Compiling help: ApplicationMain.exe : fatal error LNK1120: 1 unresolved externals

### ISSUE THREAD

**Issue by CreamslyCream** [FNF-CNE-Devs/CodenameEngine#354]
![Screenshot 2024-07-19 164033](https://github.com/user-attachments/assets/8d76a3ff-0c56-4771-8689-80f1e5432517)

[X] Windows
[ ] Linux
[ ] Mac

when i try to compile the game,  get the error, ApplicationMain.exe : fatal error LNK1120: 1 unresolved externals i have run the setup.bat looked around online and nothing helped

my haxe version is 4.2.5 if that helps

**Comment by moxie-coder** [comment]
`lime build windows -final`

**Comment by CreamslyCream** [comment]
still getting the same error

**Comment by dotaxel** [comment]
make a clean build using the -clean flag
`lime test $target -clean`
after you done it, dont use -clean again
