### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Remkich** [FNF-CNE-Devs/CodenameEngine#356]
So we have a feature convert codename chart to psych engine. so here's my question:
is it possible to convert psych engine chart to codename?

**Comment by NexIsDumb** [comment]
yes, just place the psych chart file and cne is gonna read it anyways and then if you want you can save it as cne chart under "file" in the chart editor

**Comment by Remkich** [comment]
Tysm bro

**Comment by NexIsDumb** [comment]
np!
