### ISSUE TITLE
Compiling help: 

### ISSUE THREAD

**Issue by IPepperMintZ** [FNF-CNE-Devs/CodenameEngine#361]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[x] Linux
[ ] Mac

### Explain your issue
i get this every time i compile the game
source/funkin/editors/EditorTreeMenu.hx:7: lines 7-31 : Loop in class building prevent compiler termination (funkin.options.TreeMenu)
##### Please check first if your issue haven't already been reported yet, and make sure you ran the `update.bat` file before building.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
![image](https://github.com/user-attachments/assets/756bc20e-c6bd-4934-9552-39d4647ddddf)

**Comment by MistyDoesStuff** [comment]
i posted the wrong screenshot,
![image](https://github.com/user-attachments/assets/2ba9f242-ac2a-4ffd-9393-6d3fb65805a7)

**Comment by moxie-coder** [comment]
it says they recommend you use 4.2.5, not 4.3

**Comment by moxie-coder** [comment]
I’ve had a similar issue with 4.3, but 4.2.5 doesn’t have this problem

**Comment by MistyDoesStuff** [comment]
> I’ve had a similar issue with 4.3, but 4.2.5 doesn’t have this problem

hello how do i switch to haxe 4.2.5?

**Comment by NexIsDumb** [comment]
> > I’ve had a similar issue with 4.3, but 4.2.5 doesn’t have this problem
> 
> 
> 
> hello how do i switch to haxe 4.2.5?

just download it from haxe's website normally

**Comment by NexIsDumb** [comment]
i think this aged, hopefully you solved it
