### ISSUE TITLE
Bug Report: My FPS drops depending on the size of the window

### ISSUE THREAD

**Issue by 14thBananaKing** [FNF-CNE-Devs/CodenameEngine#384]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
When I first open the game, the fps is completely fine, at a stable 120. But if I increase the size of the window it lowers my fps by a lot, maximizing it keeps my fps at 24 until I make it smaller again.
![Screenshot 2024-09-22 191504](https://github.com/user-attachments/assets/b8f70e6c-381b-4e03-8609-83a9efbd9547)
![Screenshot 2024-09-22 191536](https://github.com/user-attachments/assets/9616fb82-037f-4af5-b526-5cd2ccf46d11)

**Comment by PetscopF** [comment]
This might be something with the rendering. I tend to not change my resolution, so I don't usually have this problem, but this certainly could happen depending on specific factors.

**Comment by 14thBananaKing** [comment]
> This might be something with the rendering. I tend to not change my resolution, so I don't usually have this problem, but this certainly could happen depending on specific factors.

Do you know any way to fix it?

**Comment by PetscopF** [comment]
> Do you know any way to fix it?

As of right now, not exactly. It could generally depend on the renderer itself, which I don't know how it works. Does this affect the entire game, or just the Warning state?

**Comment by 14thBananaKing** [comment]
> As of right now, not exactly. It could generally depend on the renderer itself, which I don't know how it works. Does this affect the entire game, or just the Warning state?

It affects the entire game

**Comment by PetscopF** [comment]
> It affects the entire game

Does the rest of the performance change as well (for example, the memory and CPU usage)?

**Comment by 14thBananaKing** [comment]
> Does the rest of the performance change as well (for example, the memory and CPU usage)?

No, only the fps is affected

**Comment by PetscopF** [comment]
> No, only the fps is affected

I just tested this myself (albeit on a slightly outdated version), but my FPS remains at a stable 120, regardless of whether or not I have a different window size (like fullscreen, for example) despite the fact that my monitor isn't exactly wide enough to support the entire game in fullscreen. I'm guessing then that it might be as a result of something within your computer? I use a desktop Windows 11 computer, so there's a chance that yours might be interfering then.

**Comment by 14thBananaKing** [comment]
> I just tested this myself (albeit on a slightly outdated version), but my FPS remains at a stable 120, regardless of whether or not I have a different window size (like fullscreen, for example) despite the fact that my monitor isn't exactly wide enough to support the entire game in fullscreen. I'm guessing then that it might be as a result of something within your computer? I use a desktop Windows 11 computer, so there's a chance that yours might be interfering then.

I'm also on windows 11, maybe it's a problem with the most recent version of cne, cause that's what I'm using

**Comment by PetscopF** [comment]
> I'm also on windows 11, maybe it's a problem with the most recent version of cne, cause that's what I'm using

I've just tested this on the most recent Windows action build; I do not have this issue on my end. It is likely something to do with your hardware in that case.

![image](https://github.com/user-attachments/assets/957af642-6779-4c4d-afeb-59dfa3d77037)

**Comment by NexIsDumb** [comment]
well this highly depends on how much outdated are your hardware components like gpu mainly

**Comment by 14thBananaKing** [comment]
It turns out this has absolutely nothing to do with the game so I'm closing this issue

**Comment by 14thBananaKing** [comment]
> just cause im curious, was i right? like hardware issues or something?

Yeah, I did some research and I saw a reddit post of someone with the same situation, and they had to change their monitor settings and stuff

**Comment by NexIsDumb** [comment]
> > just cause im curious, was i right? like hardware issues or something?
> 
> Yeah, I did some research and I saw a reddit post of someone with the same situation, and they had to change their monitor settings and stuff

ah i see
