### ISSUE TITLE
"Could not find a sound asset with the name 'Voices.ogg'." Well duh, I'm using vocal suffixes

### ISSUE THREAD

**Issue by KadePleaseHelpMe** [FNF-CNE-Devs/CodenameEngine#401]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

### Explain your issue
In the chart editor, I keep getting this error whenever I open a song with vocal suffixes
![image](https://github.com/user-attachments/assets/b6ca051a-f0b5-42f1-9ff2-fd6a2c5a0f02)
I'm not sure if this is a code oversight or just an annoying crappy message, but it's annoying to receive every time I open this song for charting.

##### Please check first if your issue haven't already been reported yet.
I haven't seen anybody else report this error, so I'm alerting y'all right now of this occurrence. Please fix asap.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by cookiesock** [comment]
we already know about it, at least wizard does
i haven't updated my dev build in months so i don't know if they've fixed it or not (or if they're even aware of it)
i told them in the dev server just in case though

**Comment by KadePleaseHelpMe** [comment]
tysm! yeah when it does get fixed I'll keep an eye out for it
