### ISSUE TITLE
Chart Editor keeps saving my charts as Bopeebo

### ISSUE THREAD

**Issue by KadePleaseHelpMe** [FNF-CNE-Devs/CodenameEngine#402]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[X] Windows
[ ] Linux
[ ] Mac

### Explain your issue
For whatever reason, whenever I save my charts to the respective files, it just saves it as Bopeebo, complete with "dad" and "bf" as the characters. The only thing unchanged is the stage and scroll speed. I have no clue why this could be happening.

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
![image](https://github.com/user-attachments/assets/3d61ed22-af96-47be-aa49-a8d96c643551)

**Comment by swordcube** [comment]
Did you base the chart off of Bopeebo?

**Comment by KadePleaseHelpMe** [comment]
Basically, I'm trying to port a Psych Engine mod to Codename. I copied and pasted a blank codename chart into each one with default data (player1: bf, player2: dad, no gf, no notes) and now every time I save, it just pastes Bopeebo. It's not even the blank chart I started with; it recreates the chart and camera events of Bopeebo every time I save. Thankfully, I managed to fix this by manually going into VSCode and typing an entire chart in JSON codename format and now it works (I think).

**Comment by swordcube** [comment]
> Basically, I'm trying to port a Psych Engine mod to Codename. I copied and pasted a blank codename chart into each one with default data (player1: bf, player2: dad, no gf, no notes) and now every time I save, it just pastes Bopeebo. It's not even the blank chart I started with; it recreates the chart and camera events of Bopeebo every time I save. Thankfully, I managed to fix this by manually going into VSCode and typing an entire chart in JSON codename format and now it works (I think). I'll reopen this issue if it comes back and I'll include more details as well. I have a problem with posting an issue/discussion and then, before anyone can respond, finding a fix. It's kind of annoying despite the fact it's a great skill to have.

Does it do that if you use Save instead of Save As

**Comment by KadePleaseHelpMe** [comment]
I used Save As. Whenever I save I have the json open behind the minimized window so I can see changes live, but it just changed it to Bopeebo instead. One thing of note is that the stage and scroll speed never changed. Only the player1, player2, and notes changed.
