### ISSUE TITLE
Bug Report: Dialogue Sound Missing

### ISSUE THREAD

**Issue by KadePleaseHelpMe** [FNF-CNE-Devs/CodenameEngine#404]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[X] Windows
[ ] Linux
[ ] Mac

### Explain your issue
There's no text.ogg in the files. Please add that. It's not even really a bug, it's just a little goof
##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
![image](https://github.com/user-attachments/assets/c49a0e11-d3bb-4e48-9141-4652db227b21)

**Comment by NexIsDumb** [comment]
well i left that one there for mods to use it, but if you suggest we should, then which sound should we use even, getting one from other engines would suck honestly lol

**Comment by NexIsDumb** [comment]
actually its better not, cuz if people want no sounds theyd have to create a script to mute it, its better like this on default

**Comment by NexIsDumb** [comment]
> well i left that one there for mods to use it, its not a bug, but if you suggest we should, then which sound should we use even, getting one from other engines would suck honestly lol

(also senpai's box dialogue uses it)
