### ISSUE TITLE
(unknown) : Type not found : openfl.utils._internal.ExtraParamsMacro

### ISSUE THREAD

**Issue by KadePleaseHelpMe** [FNF-CNE-Devs/CodenameEngine#441]
### Discussed in https://github.com/FNF-CNE-Devs/CodenameEngine/discussions/440

<div type='discussions-op-text'>

<sup>Originally posted by **KadePleaseHelpMe** November 11, 2024</sup>
Ran update.bat and then got this error. Solution?
![image](https://github.com/user-attachments/assets/89d1e959-352e-4505-ab48-990694389dfb)
</div>

**Comment by PetscopF** [comment]
That's on OpenFL's part. You could try deleting the local Haxe libraries folder first and then rerun the script; if it does not work, then I'm not sure what would be the correct solution for this.

**Comment by KadePleaseHelpMe** [comment]
Nex previously responded to this in discussions and it was the correct thing! Thank you anyway, but the problem is now fixed!
