### ISSUE TITLE
The game can crash if you try to access Codename Credits without internet

### ISSUE THREAD

**Issue by KadePleaseHelpMe** [FNF-CNE-Devs/CodenameEngine#442]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[X] Windows (I imagine this happens on every device, but I use Windows so HAH)
[ ] Linux
[ ] Mac

Let's say you're a bored 15 year old who isn't tired and has his crusty laptop on a 14 hour car ride. You get bored and want to go play your favorite game, Friday Night Funkin--specifically, your Codename Engine mod. You get curious and go to the codename credits. Suddenly, your console spits back a shitload of errors and your game crashes. This is because, on a car ride, you have no internet. Therefore, this happens.
![image](https://github.com/user-attachments/assets/027a0a8e-e64d-4327-9002-6e46d7a45777)
This doubles as an enhancement issue. Can we please add a UIWarningSubstate that says "hey doofus connect to wifi to see wifi things"?

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by PetscopF** [comment]
> ### Which target are you using?
> 
> [X] Windows (I imagine this happens on every device, but I use Windows so HAH) [ ] Linux [ ] Mac
> 
> Let's say you're a bored 15 year old who isn't tired and has his crusty laptop on a 14 hour car ride. You get bored and want to go play your favorite game, Friday Night Funkin--specifically, your Codename Engine mod. You get curious and go to the codename credits. Suddenly, your console spits back a shitload of errors and your game crashes. This is because, on a car ride, you have no internet. Therefore, this happens. ![image](https://private-user-images.githubusercontent.com/89645987/385563906-027a0a8e-e64d-4327-9002-6e46d7a45777.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzI0MzYsIm5iZiI6MTczMTQ3MjEzNiwicGF0aCI6Ii84OTY0NTk4Ny8zODU1NjM5MDYtMDI3YTBhOGUtZTY0ZC00MzI3LTkwMDItNmU0NmQ3YTQ1Nzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA0Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MzUyODNkM2ZjMjM1Mjk4NTlkYWVmZjg0YzJlOThkNzI1NjM1ZTA1MDRjZTI2ODc0ZDE3YjZlYjc4ZTgzMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sCgEhKhJ_fKw0oNtPPxMNm-S4gBzY3gG7Eb3ApE2_0I) This doubles as an enhancement issue. Can we please add a UIWarningSubstate that says "hey doofus connect to wifi to see wifi things"?
> ##### Please check first if your issue haven't already been reported yet.

I'm guessing it has at the very least to do with the fact that it checks GitHub in real-time, so that's probably why. My proposal would at the very least be to see if there is a connection to the Internet available (a connection to Wi-Fi or Ethernet wouldn't be enough, since some connections start out with no Internet access) and only make the GitHub credits available when there is an Internet connection established.

**Comment by NexIsDumb** [comment]
I coded entirely alone the credits so Im like the father of them lmfao
but i do remember EXACTLY that Ive placed a small warning window that should pop up whether theres an error there?? 'mma check later once im outta school

**Comment by NexIsDumb** [comment]
just checked it actually doesnt, it just makes a warning pop up (smth that i intentionally coded) WITHOUT crashing
