### ISSUE TITLE
Bug Report: When trying to start the game executable does nothing

### ISSUE THREAD

**Issue by AndreyAdamenco** [FNF-CNE-Devs/CodenameEngine#447]
[ ] Windows
[X] Linux
[ ] Mac

![image](https://github.com/user-attachments/assets/da5f9cab-032c-4486-b8d5-9c4b604cc005)
When trying to run the game executable does nothing. When trying to run it inside terminal it only gives the error shown on screenshot. The only thing that I changed it to be flaged as an executable. Yes I have Vlc installed but every other program is fine with that but not the engine.

**Comment by mcagabe19** [comment]
sudo apt install vlc

**Comment by Frakits** [comment]
you gotta install libvlc-dev via `sudo apt install libvlc-dev`. after that it should run

**Comment by PetscopF** [comment]
> Yes I have Vlc installed but every other program is fine with that but not the engine.

LibVLC is separate from the VLC media player. LibVLC makes up the backbone of VLC and is freely usable in other programs, including Codename Engine. As others have suggested, install it through `apt` since you are using Pop!_OS.

**Comment by AndreyAdamenco** [comment]
thanks guys for your responses I will mark it as closed because the issue is resolved
