### ISSUE TITLE
Bug Report: Psych Port Chart Editor Issue

### ISSUE THREAD

**Issue by Arachnarmidillidia** [FNF-CNE-Devs/CodenameEngine#465]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x ] Windows
[ ] Linux
[ ] Mac

https://github.com/user-attachments/assets/e900b606-c8a7-4a07-b0ca-32a65582a967

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

So i ported a chart from Psych engine into codename engine. Everything seemed fine, but i noted that some notes were missing. Yet, scrolling down showed those same notes being perfectly fine. Scrolling back up however, repeated the issue. 

In game it works perfectly well. 

I am NOT using a current build of CNE, instead, i am using a build from the 25th of November.

**Comment by NexIsDumb** [comment]
literally right now we just pushed a new commit that fixed some stuff about psych porting and added 1.0 psych chart porting, try again with the new version

**Comment by Arachnarmidillidia** [comment]
Oh lmaoo

**Comment by Arachnarmidillidia** [comment]
[hard.json](https://github.com/user-attachments/files/17963784/hard.json)
the chart

**Comment by NexIsDumb** [comment]
> [hard.json](https://github.com/user-attachments/files/17963784/hard.json) the chart

thats a codename engine chart

**Comment by NexIsDumb** [comment]
OHHHH i get now what u mean

**Comment by Arachnarmidillidia** [comment]
[perdition.json](https://github.com/user-attachments/files/17963813/perdition.json)
found the psych chart i think

**Comment by NexIsDumb** [comment]
one question as im doing though, did you manually edit the chart file?

**Comment by Arachnarmidillidia** [comment]
no, just dragged and dropped into codename

**Comment by NexIsDumb** [comment]
fixed in the discord server
