### ISSUE TITLE
Week 6 Pause Menu Scaling Is Off

### ISSUE THREAD

**Issue by SwickTheGreat** [FNF-CNE-Devs/CodenameEngine#466]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x ] Windows
[ ] Linux
[ ] Mac

### Explain your issue
The scale of the week 6 pause menu is too small and is not properly sized. I don't know what could've caused this, but it's probably an easy fix.

![image](https://github.com/user-attachments/assets/8b7796bb-2db4-443d-9556-d196322611bf)

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by NeeEoo** [comment]
Fixed
