### ISSUE TITLE
Bug Report: numbers dont appear in freeplay

### ISSUE THREAD

**Issue by GummyRon** [FNF-CNE-Devs/CodenameEngine#476]
[weed]: <numbers for freeplay song names dont appear> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <freeplay issue> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[X] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
I'm not sure if its my build or not but, songs that include numbers in the name only show the text, no numbers.
If its possible to fix it would be really helpful.
![image](https://github.com/user-attachments/assets/d59a3b90-1c45-4c2d-a956-06249b526afd)

**Comment by NeeEoo** [comment]
Right now we dont support it, theres some wip numbers in the spritesheet but you gotta add it yourself to alphabet xml

**Comment by GummyRon** [comment]
hmm
understandable

**Comment by GummyRon** [comment]
![image](https://github.com/user-attachments/assets/2a45daf7-da4b-4134-a8c1-be69f95dfa94)
managed to fix it
