### ISSUE TITLE
Bug Report: [Pixel Pause menu text glitch - GF sad not positioned correctly]

### ISSUE THREAD

**Issue by ghost** [FNF-CNE-Devs/CodenameEngine#58]
Which target are you using?
[X] Windows
[ ] Linux
[ ] Mac
Build #2052

### Explain your issue
The first issue is when pausing a song in Week 6 or Test (or whatever utilizes the Pixel Pause menu, the pause text may have some distortion or glitch. There is no errors or warnings in Console Log. 
_To recreate this glitch, enter Test or any song that uses that pause menu and simply click Enter or a keybind that pauses the song._
Display Resolution: 1920x1080 

The second issue is GF's sad note miss appears to be positioned wrong in the Test song. I'm not too sure if this applies to other songs in the game but I've noticed that GF moves to a different spot in the game instead of sticking into one spot.
To recreate this glitch, simply miss notes to trigger GF's sad animation.

You can see both GF not positioned correctly and the pause menu glitch in the same image.
![image](https://user-images.githubusercontent.com/74748724/212437640-2364b90c-0cc5-4aee-9e28-b8deed8ce142.png)

**Comment by 40U538072** [comment]
This isn't enough information to confirm the issue. Can you send a video of what's happening?

**Comment by 40U538072** [comment]
Might have to do with any settings you may have. See if disabling/enabling anti-aliasing fixes it (if it is a setting in the engine). I am new to Codename Engine and going with what I possibly can. Also, could have something to do with your graphics driver. Maybe try updating it and see if that fixes it. If not, uninstall the driver and restart the computer. It will automatically reinstall the latest version. If that doesn't work, try reinstalling Codename Engine.

**Comment by SIG7Pro** [comment]
I don't think the macOS version has the pause menu issue.
