### ISSUE TITLE
Bug Report: Controllers glitches Codename Engine

### ISSUE THREAD

**Issue by ghost** [FNF-CNE-Devs/CodenameEngine#59]
### Which target are you using?
[X] Windows
[ ] Linux
[ ] Mac
Build #2502
When connecting a Dualshock controller, the game in the beginning will work fine (except when binding buttons, I'm pretty aware Codename Engine may not support controllers yet), however when loading into a song, attempting to pause will pause for a split second before going back into the game.

Disconnecting the controller will not do anything as the game is glitched already (ex: pausing the song).

Recreate issue steps:
Connect a controller (mine was a DualShock 4)
Load Codename Engine (loading Codename first and then the controller may not recreate the issue)
Go to any song (I used Freeplay>Test)
Load the song
Attempt to pause the song using the key ENTER or in controller,, it will not work out well.

The game will also freeze if you spam any button in the beginning of the game using a controller.
![image](https://user-images.githubusercontent.com/74748724/212486382-ab958f48-9d96-41cd-b3ba-30221bbe4cb8.png)
![image](https://user-images.githubusercontent.com/74748724/212486442-7e48fb70-9fd3-4a5a-9b2a-65d971341c1d.png)

**Comment by NeeEoo** [comment]
> attempting to pause will pause for a split second before going back into the game.

this is a flixel issue sadly
