### ISSUE TITLE
Action Build won't open

### ISSUE THREAD

**Issue by AceThePan** [FNF-CNE-Devs/CodenameEngine#63]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[x] Mac

### Explain your issue
I can't open the action build :/
##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by BushTrain460615** [comment]
go to the app and two finger click on it and click open contents
<img width="257" alt="Screen Shot 2023-01-23 at 12 19 35 PM" src="https://user-images.githubusercontent.com/72326501/214118572-9afd8964-80ff-4f5e-a350-23f1efdfecab.png">
then open up contents and go to macOS folder
<img width="96" alt="Screen Shot 2023-01-23 at 12 20 22 PM" src="https://user-images.githubusercontent.com/72326501/214118717-4ff9380a-9870-4a01-9c92-662d6a047049.png">
then open terminal and type in chmod 777 and drag the CodenameEngine file into the terminal 
then click enter and type in the admin password if it asks for it 
then it should work

**Comment by BushTrain460615** [comment]
I'm on my school laptop so I can't have pictures of the terminal right now but when I get home I will take screenshots and put it on the message

**Comment by Selever4Fun** [comment]
It says "permission dienied" when I try to do it :/

> go to the app and two finger click on it and click open contents <img alt="Screen Shot 2023-01-23 at 12 19 35 PM" width="257" src="https://user-images.githubusercontent.com/72326501/214118572-9afd8964-80ff-4f5e-a350-23f1efdfecab.png"> then open up contents and go to macOS folder <img alt="Screen Shot 2023-01-23 at 12 20 22 PM" width="96" src="https://user-images.githubusercontent.com/72326501/214118717-4ff9380a-9870-4a01-9c92-662d6a047049.png"> then open terminal and type in chmod 777 and drag the CodenameEngine file into the terminal then click enter and type in the admin password if it asks for it then it should work

**Comment by BushTrain460615** [comment]
try to use sudo chmod 777

**Comment by BushTrain460615** [comment]
https://support.apple.com/guide/terminal/make-a-file-executable-apdd100908f-06b3-4e63-8a87-32e71241bab4/mac
