### ISSUE TITLE
Bug Report: girlfriend isn't synced to the beat

### ISSUE THREAD

**Issue by BombasticTom** [FNF-CNE-Devs/CodenameEngine#71]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
As shown in this video, girlfriend isn't synchronized to the song tempo correctly (probably because it's using textured atlas)

https://user-images.githubusercontent.com/85838311/216390689-ff8dd289-594b-4c9c-b79a-c8bcdd7a3d37.mp4

**Comment by SwickTheGreat** [comment]
i think gf is bopping completely fine, the bpm might be off. texture atlas has nothing to do with this.

**Comment by BombasticTom** [comment]
the bpm is right, and she's bopping on the correct time, but the speed of her bopping is inconsistent

**Comment by WizardMantis441** [comment]
her anim was made so that it works with every bpm so it may not flow perfectly, i don't think this is a bug tho?

**Comment by BombasticTom** [comment]
idk, i'm pretty sure that this wasn't present in the base game, so that's why i started a pr (i might be wrong tho)

**Comment by TheKitBoi** [comment]
https://github.com/YoshiCrafter29/CodenameEngine/blob/main/assets/data/characters/gf-tankmen.xml
u can edit the animation indices

**Comment by NeeEoo** [comment]
I dont see the issue, gf bops every beat, while dad and boyfriend bops every 2 beats.
