### ISSUE TITLE
Bug Report: FunkinSprite disappear when zooming in

### ISSUE THREAD

**Issue by Frakits** [FNF-CNE-Devs/CodenameEngine#76]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
FunkinSprites with zoomFactor 0 for some reason disappear when you zoom in the camera long enough

https://github.com/FNF-CNE-Devs/CodenameEngine/assets/90983918/f2c9c513-5e15-4cc5-bc9d-012049dc5ef1

**Comment by kittstone** [comment]
i literally told yosh about this back in the early codename engine days and he didnt do anything about it
to be honest i am still kinda pissed over that
