### ISSUE TITLE
Bug Report: No "Needs Voices" option on the new chart system.

### ISSUE THREAD

**Issue by enderpuff** [FNF-CNE-Devs/CodenameEngine#83]
This is pretty self explanatory, as there is no Needs Voices option for charts, songs like tutorial always try to load in Voices.ogg.

[ X ] Windows
[ X ] Linux
[ ] Mac

Image of the engine trying to load in Voices.ogg in a voiceless song
![image](https://user-images.githubusercontent.com/96190815/220216013-27812aa9-4519-4d74-b512-6564a5cddaf3.png)

**Comment by enderpuff** [comment]
Also another thing i find weird is the incapability of opening the chart editor, but i assume that's related to the chart system still being re-made so Yoshi will probably remake the chart editor when he finishes it, just wanted to leave that note here

**Comment by NeeEoo** [comment]
This should be fixed with ae01d8ae8390c7effec58375ca85e64df156454f, if it isnt, please reopen this issue
