### ISSUE TITLE
Bug Report: Camera is zoomed out in Thorns with Pixel Perfect Mode off

### ISSUE THREAD

**Issue by swordcube** [FNF-CNE-Devs/CodenameEngine#87]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[X] Windows
[ ] Linux
[ ] Mac

### Explain your issue
The title should explain it all but incase you can't read the title somehow

The camera is zoomed out in Thorns with Pixel Perfect Mode turned off in the Options.
No other song in Week 6 does this.

[The FlxProject in the screenshot is a screenshot border, don't worry about it]

![image](https://user-images.githubusercontent.com/49110074/220746639-f08f3713-dafb-48e9-8d57-2a7aea4a43a4.png)

**How to reproduce the bug:**
Literally just load into Thorns

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by YoshiCrafter29** [comment]
fixed
