### ISSUE TITLE
CHART EDITOR WONT OPEN? 

### ISSUE THREAD

**Issue by fueg0y** [FNF-CNE-Devs/CodenameEngine#88]
i was working on coding a mod and when i tried to press 7 on a song the chart editor didnt load at all. even when i add other states and put it to a keybind and press it it doesnt load. i think there is a problem with the keybinding or something.

[ ] Windows

**Comment by SwickTheGreat** [comment]
> i was working on coding a mod and when i tried to press 7 on a song the chart editor didnt load at all. even when i add other states and put it to a keybind and press it it doesnt load. i think there is a problem with the keybinding or something.
> 
> [ ] Windows

the chart editor was removed in a previous commit, this was intentional and was probably done because it's gonna get reworked. yoshi removed the bind because it would probably cause issues. [ close ]

**Comment by BeepSheep254** [comment]
> i was working on coding a mod and when i tried to press 7 on a song the chart editor didnt load at all. even when i add other states and put it to a keybind and press it it doesnt load. i think there is a problem with the keybinding or something.
> 
> [ ] Windows

they removed the chart editor for a reason as of now
so you would now need to figure out how the new chart system works at the moment

**Comment by UnknownSkid** [comment]
> > i was working on coding a mod and when i tried to press 7 on a song the chart editor didnt load at all. even when i add other states and put it to a keybind and press it it doesnt load. i think there is a problem with the keybinding or something.
> > [ ] Windows
> 
> they removed the chart editor for a reason as of now (and the chart keybind too, would cause issues if he didnt) so you would now need to figure out how the new chart system works at the moment

do you know which latest action had the chart editor

**Comment by NeeEoo** [comment]
I don't remember closing this tbh. But press 7 on the main menu

**Comment by CharlesCatYT** [comment]
yeah, this issue is old anyway
