### ISSUE TITLE
Add alt animation for tankman

### ISSUE THREAD

**Issue by enderpuff** [FNF-CNE-Devs/CodenameEngine#9]
During the ugh song i've noticed that there is no alt animation for the ugh note.

**Comment by MemeHoovy** [comment]
because the engine is not finished

**Comment by Enderpuff** [comment]
I know that, its exactly why i am pointing this out.

**Comment by FoxelTheFennic** [comment]
this will probably be fixed once note types are fully added

**Comment by NexIsDumb** [comment]
Fixed in the dev repo!
Will be merged soon
