### ISSUE TITLE
Compiling help: [attempted to compile the engine upon the attempt i received this error]

### ISSUE THREAD

**Issue by raymah-noodles** [FNF-CNE-Devs/CodenameEngine#91]
### using visual studio code

[x ] Windows
i tried to compile the engine but i received C:/HaxeToolkit/haxe/lib/hxCodec/git/vlc/lib/LibVLCBuild.xml as a error pls help
i havent found any fix for this isssue.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER
<img width="859" alt="ERROR" src="https://user-images.githubusercontent.com/60827380/223466890-96b4134b-4964-4885-a1e6-c736cba5e3c3.png">

**Comment by raymah-noodles** [comment]
PLS help please

**Comment by TheKitBoi** [comment]
then get this https://github.com/polybiusproxy/hxCodec/blob/main/hxcodec/vlc/LibVLCBuild.xml
and put it on the right dir

**Comment by raymah-noodles** [comment]
> then get this https://github.com/polybiusproxy/hxCodec/blob/main/hxcodec/vlc/LibVLCBuild.xml and put it on the right dir

now i received this error Error: VlcBitmap.cpp
./src/vlc/bitmap/VlcBitmap.cpp(5): fatal error C1083: Cannot open include file: 'LibVLC.h': No such file or directory @TheKitBoi 
more help pls

**Comment by raymah-noodles** [comment]
thanks but now i received this error Error: VlcBitmap.cpp
./src/vlc/bitmap/VlcBitmap.cpp(5): fatal error C1083: Cannot open include file: 'LibVLC.h': No such file or directory pls help!! @TheKitBoi

**Comment by TheKitBoi** [comment]
then get this https://github.com/polybiusproxy/hxCodec/blob/main/hxcodec/vlc/LibVLC.hx

**Comment by raymah-noodles** [comment]
> then get this https://github.com/polybiusproxy/hxCodec/blob/main/hxcodec/vlc/LibVLC.hx

still got the same error @TheKitBoi

**Comment by raymah-noodles** [comment]
turns out all i needed to do was rename the folder for codename engine

**Comment by raymah-noodles** [comment]
nvm

**Comment by NeeEoo** [comment]
Run this in desktop cmd `haxelib set hxCodec 2.5.1`

**Comment by NeeEoo** [comment]
This should be fixed now
