### ISSUE TITLE
Bug Report: Custom states doesn't work

### ISSUE THREAD

**Issue by BernardoGP4504** [FNF-CNE-Devs/CodenameEngine#93]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
When doing any custom state (like `MainMenuState` or `FreeplayState`, anything in general), It doesn't load.
I've tried restarting the engine and deleting and creating the file but nothing worked

**Comment by NeeEoo** [comment]
Please provide an small sample where this happens, like a zip of a mod where just this issue happens
