### ISSUE TITLE
Compiling help: Error on compiling the engine

### ISSUE THREAD

**Issue by Tekaruki008** [FNF-CNE-Devs/CodenameEngine#95]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ x ] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
okay so, when i was compiling the engine a error occured
Its basically:

source/funkin/options/OptionsScreen.hx:71: characters 42-43 : Int should be flixel.util.FlxAxes
source/funkin/options/OptionsScreen.hx:71: characters 42-43 : ... For optional function argument 'repeatAxes'
source/funkin/options/OptionsScreen.hx:131: characters 18-27 : flixel.addons.display.FlxBackdrop has no field loadFrame (Suggestion: drawFrame)

It can be fixed replacing "loadFrame" to "drawFrame"
But after fixing that, occured another error and that is:

source/funkin/options/OptionsScreen.hx:131: characters 28-42 : flixel.graphics.frames.FlxFrame should be Bool
source/funkin/options/OptionsScreen.hx:131: characters 28-42 : ... For optional function argument 'Force'

Idk what to do here so pls fix that and thx for read it

[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

First error:
![image](https://user-images.githubusercontent.com/127638547/230752088-14308ee5-1df5-4f2f-b781-56f3dd8def30.png)

Second error:
![image](https://user-images.githubusercontent.com/127638547/230752111-cd1e5e73-f67f-4442-9fc4-0d13da199100.png)

**Comment by YoshiCrafter29** [comment]
fixed on the newest version
