### ISSUE TITLE
Compiling Doesnt work

### ISSUE THREAD

**Issue by JwallsRBLX** [FNF-CNE-Devs/CodenameEngine#96]
Issue: source/funkin/system/MusicBeatState.hx:107: characters 43-45 : Expected )

**Comment by YoshiCrafter29** [comment]
update your haxe

**Comment by JwallsRBLX** [comment]
i did that but than it said this
 C:/Users/walls/Downloads/CodenameEngine-main/CodenameEngine-main/.haxelib/flxanimate/git/flxanimate/animate/FlxAnim.hx:29: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/walls/Downloads/CodenameEngine-main/CodenameEngine-main/.haxelib/flxanimate/git/flxanimate/FlxAnimate.hx:408: characters 97-105 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/funkin/backend/system/macros/ScriptsMacro.hx:31: characters 3-82 : Uncaught exception Invalid type definition
C:\HaxeToolkit\haxe\std/haxe/macro/Context.hx:674: characters 3-63 : Called from here
C:/Users/walls/Downloads/CodenameEngine-main/CodenameEngine-main/.haxelib/hscript-improved/git/hscript/UsingHandler.hx:98: characters 4-68 : Called from here
source/funkin/backend/system/macros/ScriptsMacro.hx:31: characters 3-82 : Called from here
