### ISSUE TITLE
Compiling help: "You must have a "project.xml" file or specify another valid project file when using the 'test' command"

### ISSUE THREAD

**Issue by slimeysonic400** [FNF-CNE-Devs/CodenameEngine#97]
![stupid lma](https://user-images.githubusercontent.com/90658302/232047871-7ad461c4-abb7-4588-8772-5245a7214ddb.PNG)
[X] Windows
[ ] Linux
[ ] Mac

When trying to compile the game, I ran into this issue after running the haxelib run lime test windows command. It still gives me an error even after checking that I have a project.xml.

**Comment by YoshiCrafter29** [comment]
you're running the command in your user directory, instead of the project's directory

try using `cd` to navigate to the project's directory and try again
