### ISSUE TITLE
Bug Report: Game crashes when I try to set a keybind

### ISSUE THREAD

**Issue by BombasticTom** [FNF-CNE-Devs/CodenameEngine#98]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.

I've downloaded the latest action build, this is what I get when changing a keybind.

![image](https://user-images.githubusercontent.com/85838311/232166045-f438d277-9d36-46cf-99d2-85bbcf780160.png)

[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by RUvlad1** [comment]
can replicate
![image](https://user-images.githubusercontent.com/60317461/232209929-203a9d05-51b6-4899-a6db-8741a9bc9620.png)

**Comment by YoshiCrafter29** [comment]
fixed
